// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usertypemock

import (
	"encoding/json"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	"github.com/asgardeo/thunder/internal/usertype"
	mock "github.com/stretchr/testify/mock"
)

// NewUserTypeServiceInterfaceMock creates a new instance of UserTypeServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserTypeServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserTypeServiceInterfaceMock {
	mock := &UserTypeServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserTypeServiceInterfaceMock is an autogenerated mock type for the UserTypeServiceInterface type
type UserTypeServiceInterfaceMock struct {
	mock.Mock
}

type UserTypeServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserTypeServiceInterfaceMock) EXPECT() *UserTypeServiceInterfaceMock_Expecter {
	return &UserTypeServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateUserType provides a mock function for the type UserTypeServiceInterfaceMock
func (_mock *UserTypeServiceInterfaceMock) CreateUserType(request usertype.CreateUserTypeRequest) (*usertype.UserType, *serviceerror.ServiceError) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserType")
	}

	var r0 *usertype.UserType
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(usertype.CreateUserTypeRequest) (*usertype.UserType, *serviceerror.ServiceError)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(usertype.CreateUserTypeRequest) *usertype.UserType); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usertype.UserType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(usertype.CreateUserTypeRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserTypeServiceInterfaceMock_CreateUserType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserType'
type UserTypeServiceInterfaceMock_CreateUserType_Call struct {
	*mock.Call
}

// CreateUserType is a helper method to define mock.On call
//   - request usertype.CreateUserTypeRequest
func (_e *UserTypeServiceInterfaceMock_Expecter) CreateUserType(request interface{}) *UserTypeServiceInterfaceMock_CreateUserType_Call {
	return &UserTypeServiceInterfaceMock_CreateUserType_Call{Call: _e.mock.On("CreateUserType", request)}
}

func (_c *UserTypeServiceInterfaceMock_CreateUserType_Call) Run(run func(request usertype.CreateUserTypeRequest)) *UserTypeServiceInterfaceMock_CreateUserType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 usertype.CreateUserTypeRequest
		if args[0] != nil {
			arg0 = args[0].(usertype.CreateUserTypeRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserTypeServiceInterfaceMock_CreateUserType_Call) Return(userType *usertype.UserType, serviceError *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_CreateUserType_Call {
	_c.Call.Return(userType, serviceError)
	return _c
}

func (_c *UserTypeServiceInterfaceMock_CreateUserType_Call) RunAndReturn(run func(request usertype.CreateUserTypeRequest) (*usertype.UserType, *serviceerror.ServiceError)) *UserTypeServiceInterfaceMock_CreateUserType_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserType provides a mock function for the type UserTypeServiceInterfaceMock
func (_mock *UserTypeServiceInterfaceMock) DeleteUserType(schemaID string) *serviceerror.ServiceError {
	ret := _mock.Called(schemaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserType")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(schemaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// UserTypeServiceInterfaceMock_DeleteUserType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserType'
type UserTypeServiceInterfaceMock_DeleteUserType_Call struct {
	*mock.Call
}

// DeleteUserType is a helper method to define mock.On call
//   - schemaID string
func (_e *UserTypeServiceInterfaceMock_Expecter) DeleteUserType(schemaID interface{}) *UserTypeServiceInterfaceMock_DeleteUserType_Call {
	return &UserTypeServiceInterfaceMock_DeleteUserType_Call{Call: _e.mock.On("DeleteUserType", schemaID)}
}

func (_c *UserTypeServiceInterfaceMock_DeleteUserType_Call) Run(run func(schemaID string)) *UserTypeServiceInterfaceMock_DeleteUserType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserTypeServiceInterfaceMock_DeleteUserType_Call) Return(serviceError *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_DeleteUserType_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *UserTypeServiceInterfaceMock_DeleteUserType_Call) RunAndReturn(run func(schemaID string) *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_DeleteUserType_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserType provides a mock function for the type UserTypeServiceInterfaceMock
func (_mock *UserTypeServiceInterfaceMock) GetUserType(schemaID string) (*usertype.UserType, *serviceerror.ServiceError) {
	ret := _mock.Called(schemaID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserType")
	}

	var r0 *usertype.UserType
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*usertype.UserType, *serviceerror.ServiceError)); ok {
		return returnFunc(schemaID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *usertype.UserType); ok {
		r0 = returnFunc(schemaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usertype.UserType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(schemaID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserTypeServiceInterfaceMock_GetUserType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserType'
type UserTypeServiceInterfaceMock_GetUserType_Call struct {
	*mock.Call
}

// GetUserType is a helper method to define mock.On call
//   - schemaID string
func (_e *UserTypeServiceInterfaceMock_Expecter) GetUserType(schemaID interface{}) *UserTypeServiceInterfaceMock_GetUserType_Call {
	return &UserTypeServiceInterfaceMock_GetUserType_Call{Call: _e.mock.On("GetUserType", schemaID)}
}

func (_c *UserTypeServiceInterfaceMock_GetUserType_Call) Run(run func(schemaID string)) *UserTypeServiceInterfaceMock_GetUserType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserTypeServiceInterfaceMock_GetUserType_Call) Return(userType *usertype.UserType, serviceError *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_GetUserType_Call {
	_c.Call.Return(userType, serviceError)
	return _c
}

func (_c *UserTypeServiceInterfaceMock_GetUserType_Call) RunAndReturn(run func(schemaID string) (*usertype.UserType, *serviceerror.ServiceError)) *UserTypeServiceInterfaceMock_GetUserType_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTypeByName provides a mock function for the type UserTypeServiceInterfaceMock
func (_mock *UserTypeServiceInterfaceMock) GetUserTypeByName(schemaName string) (*usertype.UserType, *serviceerror.ServiceError) {
	ret := _mock.Called(schemaName)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTypeByName")
	}

	var r0 *usertype.UserType
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*usertype.UserType, *serviceerror.ServiceError)); ok {
		return returnFunc(schemaName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *usertype.UserType); ok {
		r0 = returnFunc(schemaName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usertype.UserType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(schemaName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserTypeServiceInterfaceMock_GetUserTypeByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTypeByName'
type UserTypeServiceInterfaceMock_GetUserTypeByName_Call struct {
	*mock.Call
}

// GetUserTypeByName is a helper method to define mock.On call
//   - schemaName string
func (_e *UserTypeServiceInterfaceMock_Expecter) GetUserTypeByName(schemaName interface{}) *UserTypeServiceInterfaceMock_GetUserTypeByName_Call {
	return &UserTypeServiceInterfaceMock_GetUserTypeByName_Call{Call: _e.mock.On("GetUserTypeByName", schemaName)}
}

func (_c *UserTypeServiceInterfaceMock_GetUserTypeByName_Call) Run(run func(schemaName string)) *UserTypeServiceInterfaceMock_GetUserTypeByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserTypeServiceInterfaceMock_GetUserTypeByName_Call) Return(userType *usertype.UserType, serviceError *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_GetUserTypeByName_Call {
	_c.Call.Return(userType, serviceError)
	return _c
}

func (_c *UserTypeServiceInterfaceMock_GetUserTypeByName_Call) RunAndReturn(run func(schemaName string) (*usertype.UserType, *serviceerror.ServiceError)) *UserTypeServiceInterfaceMock_GetUserTypeByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTypeList provides a mock function for the type UserTypeServiceInterfaceMock
func (_mock *UserTypeServiceInterfaceMock) GetUserTypeList(limit int, offset int) (*usertype.UserTypeListResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTypeList")
	}

	var r0 *usertype.UserTypeListResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(int, int) (*usertype.UserTypeListResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) *usertype.UserTypeListResponse); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usertype.UserTypeListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserTypeServiceInterfaceMock_GetUserTypeList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTypeList'
type UserTypeServiceInterfaceMock_GetUserTypeList_Call struct {
	*mock.Call
}

// GetUserTypeList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *UserTypeServiceInterfaceMock_Expecter) GetUserTypeList(limit interface{}, offset interface{}) *UserTypeServiceInterfaceMock_GetUserTypeList_Call {
	return &UserTypeServiceInterfaceMock_GetUserTypeList_Call{Call: _e.mock.On("GetUserTypeList", limit, offset)}
}

func (_c *UserTypeServiceInterfaceMock_GetUserTypeList_Call) Run(run func(limit int, offset int)) *UserTypeServiceInterfaceMock_GetUserTypeList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserTypeServiceInterfaceMock_GetUserTypeList_Call) Return(userTypeListResponse *usertype.UserTypeListResponse, serviceError *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_GetUserTypeList_Call {
	_c.Call.Return(userTypeListResponse, serviceError)
	return _c
}

func (_c *UserTypeServiceInterfaceMock_GetUserTypeList_Call) RunAndReturn(run func(limit int, offset int) (*usertype.UserTypeListResponse, *serviceerror.ServiceError)) *UserTypeServiceInterfaceMock_GetUserTypeList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserType provides a mock function for the type UserTypeServiceInterfaceMock
func (_mock *UserTypeServiceInterfaceMock) UpdateUserType(schemaID string, request usertype.UpdateUserTypeRequest) (*usertype.UserType, *serviceerror.ServiceError) {
	ret := _mock.Called(schemaID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserType")
	}

	var r0 *usertype.UserType
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, usertype.UpdateUserTypeRequest) (*usertype.UserType, *serviceerror.ServiceError)); ok {
		return returnFunc(schemaID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(string, usertype.UpdateUserTypeRequest) *usertype.UserType); ok {
		r0 = returnFunc(schemaID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usertype.UserType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, usertype.UpdateUserTypeRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(schemaID, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserTypeServiceInterfaceMock_UpdateUserType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserType'
type UserTypeServiceInterfaceMock_UpdateUserType_Call struct {
	*mock.Call
}

// UpdateUserType is a helper method to define mock.On call
//   - schemaID string
//   - request usertype.UpdateUserTypeRequest
func (_e *UserTypeServiceInterfaceMock_Expecter) UpdateUserType(schemaID interface{}, request interface{}) *UserTypeServiceInterfaceMock_UpdateUserType_Call {
	return &UserTypeServiceInterfaceMock_UpdateUserType_Call{Call: _e.mock.On("UpdateUserType", schemaID, request)}
}

func (_c *UserTypeServiceInterfaceMock_UpdateUserType_Call) Run(run func(schemaID string, request usertype.UpdateUserTypeRequest)) *UserTypeServiceInterfaceMock_UpdateUserType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 usertype.UpdateUserTypeRequest
		if args[1] != nil {
			arg1 = args[1].(usertype.UpdateUserTypeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserTypeServiceInterfaceMock_UpdateUserType_Call) Return(userType *usertype.UserType, serviceError *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_UpdateUserType_Call {
	_c.Call.Return(userType, serviceError)
	return _c
}

func (_c *UserTypeServiceInterfaceMock_UpdateUserType_Call) RunAndReturn(run func(schemaID string, request usertype.UpdateUserTypeRequest) (*usertype.UserType, *serviceerror.ServiceError)) *UserTypeServiceInterfaceMock_UpdateUserType_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUser provides a mock function for the type UserTypeServiceInterfaceMock
func (_mock *UserTypeServiceInterfaceMock) ValidateUser(userType string, userAttributes json.RawMessage) (bool, *serviceerror.ServiceError) {
	ret := _mock.Called(userType, userAttributes)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUser")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) (bool, *serviceerror.ServiceError)); ok {
		return returnFunc(userType, userAttributes)
	}
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) bool); ok {
		r0 = returnFunc(userType, userAttributes)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, json.RawMessage) *serviceerror.ServiceError); ok {
		r1 = returnFunc(userType, userAttributes)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserTypeServiceInterfaceMock_ValidateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUser'
type UserTypeServiceInterfaceMock_ValidateUser_Call struct {
	*mock.Call
}

// ValidateUser is a helper method to define mock.On call
//   - userType string
//   - userAttributes json.RawMessage
func (_e *UserTypeServiceInterfaceMock_Expecter) ValidateUser(userType interface{}, userAttributes interface{}) *UserTypeServiceInterfaceMock_ValidateUser_Call {
	return &UserTypeServiceInterfaceMock_ValidateUser_Call{Call: _e.mock.On("ValidateUser", userType, userAttributes)}
}

func (_c *UserTypeServiceInterfaceMock_ValidateUser_Call) Run(run func(userType string, userAttributes json.RawMessage)) *UserTypeServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserTypeServiceInterfaceMock_ValidateUser_Call) Return(b bool, serviceError *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *UserTypeServiceInterfaceMock_ValidateUser_Call) RunAndReturn(run func(userType string, userAttributes json.RawMessage) (bool, *serviceerror.ServiceError)) *UserTypeServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUserUniqueness provides a mock function for the type UserTypeServiceInterfaceMock
func (_mock *UserTypeServiceInterfaceMock) ValidateUserUniqueness(userType string, userAttributes json.RawMessage, identifyUser func(map[string]interface{}) (*string, error)) (bool, *serviceerror.ServiceError) {
	ret := _mock.Called(userType, userAttributes, identifyUser)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserUniqueness")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage, func(map[string]interface{}) (*string, error)) (bool, *serviceerror.ServiceError)); ok {
		return returnFunc(userType, userAttributes, identifyUser)
	}
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage, func(map[string]interface{}) (*string, error)) bool); ok {
		r0 = returnFunc(userType, userAttributes, identifyUser)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, json.RawMessage, func(map[string]interface{}) (*string, error)) *serviceerror.ServiceError); ok {
		r1 = returnFunc(userType, userAttributes, identifyUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserUniqueness'
type UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call struct {
	*mock.Call
}

// ValidateUserUniqueness is a helper method to define mock.On call
//   - userType string
//   - userAttributes json.RawMessage
//   - identifyUser func(map[string]interface{}) (*string, error)
func (_e *UserTypeServiceInterfaceMock_Expecter) ValidateUserUniqueness(userType interface{}, userAttributes interface{}, identifyUser interface{}) *UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call {
	return &UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call{Call: _e.mock.On("ValidateUserUniqueness", userType, userAttributes, identifyUser)}
}

func (_c *UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call) Run(run func(userType string, userAttributes json.RawMessage, identifyUser func(map[string]interface{}) (*string, error))) *UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		var arg2 func(map[string]interface{}) (*string, error)
		if args[2] != nil {
			arg2 = args[2].(func(map[string]interface{}) (*string, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call) Return(b bool, serviceError *serviceerror.ServiceError) *UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call) RunAndReturn(run func(userType string, userAttributes json.RawMessage, identifyUser func(map[string]interface{}) (*string, error)) (bool, *serviceerror.ServiceError)) *UserTypeServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Return(run)
	return _c
}
