// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usertypemock

import (
	"github.com/asgardeo/thunder/internal/usertype"
	mock "github.com/stretchr/testify/mock"
)

// newUserTypeStoreInterfaceMock creates a new instance of userTypeStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newUserTypeStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *userTypeStoreInterfaceMock {
	mock := &userTypeStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// userTypeStoreInterfaceMock is an autogenerated mock type for the userTypeStoreInterface type
type userTypeStoreInterfaceMock struct {
	mock.Mock
}

type userTypeStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *userTypeStoreInterfaceMock) EXPECT() *userTypeStoreInterfaceMock_Expecter {
	return &userTypeStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateUserType provides a mock function for the type userTypeStoreInterfaceMock
func (_mock *userTypeStoreInterfaceMock) CreateUserType(userType usertype.UserType) error {
	ret := _mock.Called(userType)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserType")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(usertype.UserType) error); ok {
		r0 = returnFunc(userType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userTypeStoreInterfaceMock_CreateUserType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserType'
type userTypeStoreInterfaceMock_CreateUserType_Call struct {
	*mock.Call
}

// CreateUserType is a helper method to define mock.On call
//   - userType usertype.UserType
func (_e *userTypeStoreInterfaceMock_Expecter) CreateUserType(userType interface{}) *userTypeStoreInterfaceMock_CreateUserType_Call {
	return &userTypeStoreInterfaceMock_CreateUserType_Call{Call: _e.mock.On("CreateUserType", userType)}
}

func (_c *userTypeStoreInterfaceMock_CreateUserType_Call) Run(run func(userType usertype.UserType)) *userTypeStoreInterfaceMock_CreateUserType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 usertype.UserType
		if args[0] != nil {
			arg0 = args[0].(usertype.UserType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *userTypeStoreInterfaceMock_CreateUserType_Call) Return(err error) *userTypeStoreInterfaceMock_CreateUserType_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userTypeStoreInterfaceMock_CreateUserType_Call) RunAndReturn(run func(userType usertype.UserType) error) *userTypeStoreInterfaceMock_CreateUserType_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserTypeByID provides a mock function for the type userTypeStoreInterfaceMock
func (_mock *userTypeStoreInterfaceMock) DeleteUserTypeByID(schemaID string) error {
	ret := _mock.Called(schemaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserTypeByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(schemaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userTypeStoreInterfaceMock_DeleteUserTypeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserTypeByID'
type userTypeStoreInterfaceMock_DeleteUserTypeByID_Call struct {
	*mock.Call
}

// DeleteUserTypeByID is a helper method to define mock.On call
//   - schemaID string
func (_e *userTypeStoreInterfaceMock_Expecter) DeleteUserTypeByID(schemaID interface{}) *userTypeStoreInterfaceMock_DeleteUserTypeByID_Call {
	return &userTypeStoreInterfaceMock_DeleteUserTypeByID_Call{Call: _e.mock.On("DeleteUserTypeByID", schemaID)}
}

func (_c *userTypeStoreInterfaceMock_DeleteUserTypeByID_Call) Run(run func(schemaID string)) *userTypeStoreInterfaceMock_DeleteUserTypeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *userTypeStoreInterfaceMock_DeleteUserTypeByID_Call) Return(err error) *userTypeStoreInterfaceMock_DeleteUserTypeByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userTypeStoreInterfaceMock_DeleteUserTypeByID_Call) RunAndReturn(run func(schemaID string) error) *userTypeStoreInterfaceMock_DeleteUserTypeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTypeByID provides a mock function for the type userTypeStoreInterfaceMock
func (_mock *userTypeStoreInterfaceMock) GetUserTypeByID(schemaID string) (usertype.UserType, error) {
	ret := _mock.Called(schemaID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTypeByID")
	}

	var r0 usertype.UserType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (usertype.UserType, error)); ok {
		return returnFunc(schemaID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) usertype.UserType); ok {
		r0 = returnFunc(schemaID)
	} else {
		r0 = ret.Get(0).(usertype.UserType)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(schemaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userTypeStoreInterfaceMock_GetUserTypeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTypeByID'
type userTypeStoreInterfaceMock_GetUserTypeByID_Call struct {
	*mock.Call
}

// GetUserTypeByID is a helper method to define mock.On call
//   - schemaID string
func (_e *userTypeStoreInterfaceMock_Expecter) GetUserTypeByID(schemaID interface{}) *userTypeStoreInterfaceMock_GetUserTypeByID_Call {
	return &userTypeStoreInterfaceMock_GetUserTypeByID_Call{Call: _e.mock.On("GetUserTypeByID", schemaID)}
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeByID_Call) Run(run func(schemaID string)) *userTypeStoreInterfaceMock_GetUserTypeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeByID_Call) Return(userType usertype.UserType, err error) *userTypeStoreInterfaceMock_GetUserTypeByID_Call {
	_c.Call.Return(userType, err)
	return _c
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeByID_Call) RunAndReturn(run func(schemaID string) (usertype.UserType, error)) *userTypeStoreInterfaceMock_GetUserTypeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTypeByName provides a mock function for the type userTypeStoreInterfaceMock
func (_mock *userTypeStoreInterfaceMock) GetUserTypeByName(name string) (usertype.UserType, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTypeByName")
	}

	var r0 usertype.UserType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (usertype.UserType, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) usertype.UserType); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(usertype.UserType)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userTypeStoreInterfaceMock_GetUserTypeByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTypeByName'
type userTypeStoreInterfaceMock_GetUserTypeByName_Call struct {
	*mock.Call
}

// GetUserTypeByName is a helper method to define mock.On call
//   - name string
func (_e *userTypeStoreInterfaceMock_Expecter) GetUserTypeByName(name interface{}) *userTypeStoreInterfaceMock_GetUserTypeByName_Call {
	return &userTypeStoreInterfaceMock_GetUserTypeByName_Call{Call: _e.mock.On("GetUserTypeByName", name)}
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeByName_Call) Run(run func(name string)) *userTypeStoreInterfaceMock_GetUserTypeByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeByName_Call) Return(userType usertype.UserType, err error) *userTypeStoreInterfaceMock_GetUserTypeByName_Call {
	_c.Call.Return(userType, err)
	return _c
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeByName_Call) RunAndReturn(run func(name string) (usertype.UserType, error)) *userTypeStoreInterfaceMock_GetUserTypeByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTypeList provides a mock function for the type userTypeStoreInterfaceMock
func (_mock *userTypeStoreInterfaceMock) GetUserTypeList(limit int, offset int) ([]usertype.UserTypeListItem, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTypeList")
	}

	var r0 []usertype.UserTypeListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]usertype.UserTypeListItem, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []usertype.UserTypeListItem); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usertype.UserTypeListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userTypeStoreInterfaceMock_GetUserTypeList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTypeList'
type userTypeStoreInterfaceMock_GetUserTypeList_Call struct {
	*mock.Call
}

// GetUserTypeList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *userTypeStoreInterfaceMock_Expecter) GetUserTypeList(limit interface{}, offset interface{}) *userTypeStoreInterfaceMock_GetUserTypeList_Call {
	return &userTypeStoreInterfaceMock_GetUserTypeList_Call{Call: _e.mock.On("GetUserTypeList", limit, offset)}
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeList_Call) Run(run func(limit int, offset int)) *userTypeStoreInterfaceMock_GetUserTypeList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeList_Call) Return(userTypeListItems []usertype.UserTypeListItem, err error) *userTypeStoreInterfaceMock_GetUserTypeList_Call {
	_c.Call.Return(userTypeListItems, err)
	return _c
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeList_Call) RunAndReturn(run func(limit int, offset int) ([]usertype.UserTypeListItem, error)) *userTypeStoreInterfaceMock_GetUserTypeList_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTypeListCount provides a mock function for the type userTypeStoreInterfaceMock
func (_mock *userTypeStoreInterfaceMock) GetUserTypeListCount() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserTypeListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userTypeStoreInterfaceMock_GetUserTypeListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTypeListCount'
type userTypeStoreInterfaceMock_GetUserTypeListCount_Call struct {
	*mock.Call
}

// GetUserTypeListCount is a helper method to define mock.On call
func (_e *userTypeStoreInterfaceMock_Expecter) GetUserTypeListCount() *userTypeStoreInterfaceMock_GetUserTypeListCount_Call {
	return &userTypeStoreInterfaceMock_GetUserTypeListCount_Call{Call: _e.mock.On("GetUserTypeListCount")}
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeListCount_Call) Run(run func()) *userTypeStoreInterfaceMock_GetUserTypeListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeListCount_Call) Return(n int, err error) *userTypeStoreInterfaceMock_GetUserTypeListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *userTypeStoreInterfaceMock_GetUserTypeListCount_Call) RunAndReturn(run func() (int, error)) *userTypeStoreInterfaceMock_GetUserTypeListCount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserTypeByID provides a mock function for the type userTypeStoreInterfaceMock
func (_mock *userTypeStoreInterfaceMock) UpdateUserTypeByID(schemaID string, userType usertype.UserType) error {
	ret := _mock.Called(schemaID, userType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserTypeByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, usertype.UserType) error); ok {
		r0 = returnFunc(schemaID, userType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userTypeStoreInterfaceMock_UpdateUserTypeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserTypeByID'
type userTypeStoreInterfaceMock_UpdateUserTypeByID_Call struct {
	*mock.Call
}

// UpdateUserTypeByID is a helper method to define mock.On call
//   - schemaID string
//   - userType usertype.UserType
func (_e *userTypeStoreInterfaceMock_Expecter) UpdateUserTypeByID(schemaID interface{}, userType interface{}) *userTypeStoreInterfaceMock_UpdateUserTypeByID_Call {
	return &userTypeStoreInterfaceMock_UpdateUserTypeByID_Call{Call: _e.mock.On("UpdateUserTypeByID", schemaID, userType)}
}

func (_c *userTypeStoreInterfaceMock_UpdateUserTypeByID_Call) Run(run func(schemaID string, userType usertype.UserType)) *userTypeStoreInterfaceMock_UpdateUserTypeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 usertype.UserType
		if args[1] != nil {
			arg1 = args[1].(usertype.UserType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userTypeStoreInterfaceMock_UpdateUserTypeByID_Call) Return(err error) *userTypeStoreInterfaceMock_UpdateUserTypeByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userTypeStoreInterfaceMock_UpdateUserTypeByID_Call) RunAndReturn(run func(schemaID string, userType usertype.UserType) error) *userTypeStoreInterfaceMock_UpdateUserTypeByID_Call {
	_c.Call.Return(run)
	return _c
}
