// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package template

import (
	"context"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewTemplateServiceInterfaceMock creates a new instance of TemplateServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateServiceInterfaceMock {
	mock := &TemplateServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TemplateServiceInterfaceMock is an autogenerated mock type for the TemplateServiceInterface type
type TemplateServiceInterfaceMock struct {
	mock.Mock
}

type TemplateServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateServiceInterfaceMock) EXPECT() *TemplateServiceInterfaceMock_Expecter {
	return &TemplateServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetTemplateByScenario provides a mock function for the type TemplateServiceInterfaceMock
func (_mock *TemplateServiceInterfaceMock) GetTemplateByScenario(ctx context.Context, scenario ScenarioType) (*TemplateDTO, *serviceerror.I18nServiceError) {
	ret := _mock.Called(ctx, scenario)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByScenario")
	}

	var r0 *TemplateDTO
	var r1 *serviceerror.I18nServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ScenarioType) (*TemplateDTO, *serviceerror.I18nServiceError)); ok {
		return returnFunc(ctx, scenario)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ScenarioType) *TemplateDTO); ok {
		r0 = returnFunc(ctx, scenario)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TemplateDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ScenarioType) *serviceerror.I18nServiceError); ok {
		r1 = returnFunc(ctx, scenario)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.I18nServiceError)
		}
	}
	return r0, r1
}

// TemplateServiceInterfaceMock_GetTemplateByScenario_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateByScenario'
type TemplateServiceInterfaceMock_GetTemplateByScenario_Call struct {
	*mock.Call
}

// GetTemplateByScenario is a helper method to define mock.On call
//   - ctx context.Context
//   - scenario ScenarioType
func (_e *TemplateServiceInterfaceMock_Expecter) GetTemplateByScenario(ctx interface{}, scenario interface{}) *TemplateServiceInterfaceMock_GetTemplateByScenario_Call {
	return &TemplateServiceInterfaceMock_GetTemplateByScenario_Call{Call: _e.mock.On("GetTemplateByScenario", ctx, scenario)}
}

func (_c *TemplateServiceInterfaceMock_GetTemplateByScenario_Call) Run(run func(ctx context.Context, scenario ScenarioType)) *TemplateServiceInterfaceMock_GetTemplateByScenario_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ScenarioType
		if args[1] != nil {
			arg1 = args[1].(ScenarioType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TemplateServiceInterfaceMock_GetTemplateByScenario_Call) Return(templateDTO *TemplateDTO, i18nServiceError *serviceerror.I18nServiceError) *TemplateServiceInterfaceMock_GetTemplateByScenario_Call {
	_c.Call.Return(templateDTO, i18nServiceError)
	return _c
}

func (_c *TemplateServiceInterfaceMock_GetTemplateByScenario_Call) RunAndReturn(run func(ctx context.Context, scenario ScenarioType) (*TemplateDTO, *serviceerror.I18nServiceError)) *TemplateServiceInterfaceMock_GetTemplateByScenario_Call {
	_c.Call.Return(run)
	return _c
}

// Render provides a mock function for the type TemplateServiceInterfaceMock
func (_mock *TemplateServiceInterfaceMock) Render(ctx context.Context, scenario ScenarioType, data TemplateData) (*RenderedTemplate, *serviceerror.I18nServiceError) {
	ret := _mock.Called(ctx, scenario, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 *RenderedTemplate
	var r1 *serviceerror.I18nServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, ScenarioType, TemplateData) (*RenderedTemplate, *serviceerror.I18nServiceError)); ok {
		return returnFunc(ctx, scenario, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ScenarioType, TemplateData) *RenderedTemplate); ok {
		r0 = returnFunc(ctx, scenario, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RenderedTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ScenarioType, TemplateData) *serviceerror.I18nServiceError); ok {
		r1 = returnFunc(ctx, scenario, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.I18nServiceError)
		}
	}
	return r0, r1
}

// TemplateServiceInterfaceMock_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type TemplateServiceInterfaceMock_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - scenario ScenarioType
//   - data TemplateData
func (_e *TemplateServiceInterfaceMock_Expecter) Render(ctx interface{}, scenario interface{}, data interface{}) *TemplateServiceInterfaceMock_Render_Call {
	return &TemplateServiceInterfaceMock_Render_Call{Call: _e.mock.On("Render", ctx, scenario, data)}
}

func (_c *TemplateServiceInterfaceMock_Render_Call) Run(run func(ctx context.Context, scenario ScenarioType, data TemplateData)) *TemplateServiceInterfaceMock_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ScenarioType
		if args[1] != nil {
			arg1 = args[1].(ScenarioType)
		}
		var arg2 TemplateData
		if args[2] != nil {
			arg2 = args[2].(TemplateData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TemplateServiceInterfaceMock_Render_Call) Return(renderedTemplate *RenderedTemplate, i18nServiceError *serviceerror.I18nServiceError) *TemplateServiceInterfaceMock_Render_Call {
	_c.Call.Return(renderedTemplate, i18nServiceError)
	return _c
}

func (_c *TemplateServiceInterfaceMock_Render_Call) RunAndReturn(run func(ctx context.Context, scenario ScenarioType, data TemplateData) (*RenderedTemplate, *serviceerror.I18nServiceError)) *TemplateServiceInterfaceMock_Render_Call {
	_c.Call.Return(run)
	return _c
}
