// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ou

import (
	"context"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewDisplayAttributeResolverMock creates a new instance of DisplayAttributeResolverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDisplayAttributeResolverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DisplayAttributeResolverMock {
	mock := &DisplayAttributeResolverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DisplayAttributeResolverMock is an autogenerated mock type for the DisplayAttributeResolver type
type DisplayAttributeResolverMock struct {
	mock.Mock
}

type DisplayAttributeResolverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DisplayAttributeResolverMock) EXPECT() *DisplayAttributeResolverMock_Expecter {
	return &DisplayAttributeResolverMock_Expecter{mock: &_m.Mock}
}

// GetDisplayAttributesByNames provides a mock function for the type DisplayAttributeResolverMock
func (_mock *DisplayAttributeResolverMock) GetDisplayAttributesByNames(ctx context.Context, names []string) (map[string]string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for GetDisplayAttributesByNames")
	}

	var r0 map[string]string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, names)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = returnFunc(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, names)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisplayAttributesByNames'
type DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call struct {
	*mock.Call
}

// GetDisplayAttributesByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
func (_e *DisplayAttributeResolverMock_Expecter) GetDisplayAttributesByNames(ctx interface{}, names interface{}) *DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call {
	return &DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call{Call: _e.mock.On("GetDisplayAttributesByNames", ctx, names)}
}

func (_c *DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call) Run(run func(ctx context.Context, names []string)) *DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call) Return(stringToString map[string]string, serviceError *serviceerror.ServiceError) *DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call {
	_c.Call.Return(stringToString, serviceError)
	return _c
}

func (_c *DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call) RunAndReturn(run func(ctx context.Context, names []string) (map[string]string, *serviceerror.ServiceError)) *DisplayAttributeResolverMock_GetDisplayAttributesByNames_Call {
	_c.Call.Return(run)
	return _c
}
