// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transactionmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTransactionerMock creates a new instance of TransactionerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionerMock {
	mock := &TransactionerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionerMock is an autogenerated mock type for the Transactioner type
type TransactionerMock struct {
	mock.Mock
}

type TransactionerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionerMock) EXPECT() *TransactionerMock_Expecter {
	return &TransactionerMock_Expecter{mock: &_m.Mock}
}

// Transact provides a mock function for the type TransactionerMock
func (_mock *TransactionerMock) Transact(ctx context.Context, txFunc func(context.Context) error) error {
	ret := _mock.Called(ctx, txFunc)

	if len(ret) == 0 {
		panic("no return value specified for Transact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = returnFunc(ctx, txFunc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionerMock_Transact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transact'
type TransactionerMock_Transact_Call struct {
	*mock.Call
}

// Transact is a helper method to define mock.On call
//   - ctx context.Context
//   - txFunc func(context.Context) error
func (_e *TransactionerMock_Expecter) Transact(ctx interface{}, txFunc interface{}) *TransactionerMock_Transact_Call {
	return &TransactionerMock_Transact_Call{Call: _e.mock.On("Transact", ctx, txFunc)}
}

func (_c *TransactionerMock_Transact_Call) Run(run func(ctx context.Context, txFunc func(context.Context) error)) *TransactionerMock_Transact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionerMock_Transact_Call) Return(err error) *TransactionerMock_Transact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionerMock_Transact_Call) RunAndReturn(run func(ctx context.Context, txFunc func(context.Context) error) error) *TransactionerMock_Transact_Call {
	_c.Call.Return(run)
	return _c
}
