// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resolvemock

import (
	"github.com/asgardeo/thunder/internal/design/common"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewDesignResolveServiceInterfaceMock creates a new instance of DesignResolveServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDesignResolveServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DesignResolveServiceInterfaceMock {
	mock := &DesignResolveServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DesignResolveServiceInterfaceMock is an autogenerated mock type for the DesignResolveServiceInterface type
type DesignResolveServiceInterfaceMock struct {
	mock.Mock
}

type DesignResolveServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DesignResolveServiceInterfaceMock) EXPECT() *DesignResolveServiceInterfaceMock_Expecter {
	return &DesignResolveServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// ResolveDesign provides a mock function for the type DesignResolveServiceInterfaceMock
func (_mock *DesignResolveServiceInterfaceMock) ResolveDesign(resolveType common.DesignResolveType, id string) (*common.DesignResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(resolveType, id)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDesign")
	}

	var r0 *common.DesignResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(common.DesignResolveType, string) (*common.DesignResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(resolveType, id)
	}
	if returnFunc, ok := ret.Get(0).(func(common.DesignResolveType, string) *common.DesignResponse); ok {
		r0 = returnFunc(resolveType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.DesignResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(common.DesignResolveType, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(resolveType, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// DesignResolveServiceInterfaceMock_ResolveDesign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDesign'
type DesignResolveServiceInterfaceMock_ResolveDesign_Call struct {
	*mock.Call
}

// ResolveDesign is a helper method to define mock.On call
//   - resolveType common.DesignResolveType
//   - id string
func (_e *DesignResolveServiceInterfaceMock_Expecter) ResolveDesign(resolveType interface{}, id interface{}) *DesignResolveServiceInterfaceMock_ResolveDesign_Call {
	return &DesignResolveServiceInterfaceMock_ResolveDesign_Call{Call: _e.mock.On("ResolveDesign", resolveType, id)}
}

func (_c *DesignResolveServiceInterfaceMock_ResolveDesign_Call) Run(run func(resolveType common.DesignResolveType, id string)) *DesignResolveServiceInterfaceMock_ResolveDesign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.DesignResolveType
		if args[0] != nil {
			arg0 = args[0].(common.DesignResolveType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DesignResolveServiceInterfaceMock_ResolveDesign_Call) Return(designResponse *common.DesignResponse, serviceError *serviceerror.ServiceError) *DesignResolveServiceInterfaceMock_ResolveDesign_Call {
	_c.Call.Return(designResponse, serviceError)
	return _c
}

func (_c *DesignResolveServiceInterfaceMock_ResolveDesign_Call) RunAndReturn(run func(resolveType common.DesignResolveType, id string) (*common.DesignResponse, *serviceerror.ServiceError)) *DesignResolveServiceInterfaceMock_ResolveDesign_Call {
	_c.Call.Return(run)
	return _c
}
