// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resource

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newResourceStoreInterfaceMock creates a new instance of resourceStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newResourceStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *resourceStoreInterfaceMock {
	mock := &resourceStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// resourceStoreInterfaceMock is an autogenerated mock type for the resourceStoreInterface type
type resourceStoreInterfaceMock struct {
	mock.Mock
}

type resourceStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *resourceStoreInterfaceMock) EXPECT() *resourceStoreInterfaceMock_Expecter {
	return &resourceStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CheckActionHandleExists provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckActionHandleExists(ctx context.Context, resServerInternalID int, resInternalID *int, handle string) (bool, error) {
	ret := _mock.Called(ctx, resServerInternalID, resInternalID, handle)

	if len(ret) == 0 {
		panic("no return value specified for CheckActionHandleExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int, string) (bool, error)); ok {
		return returnFunc(ctx, resServerInternalID, resInternalID, handle)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int, string) bool); ok {
		r0 = returnFunc(ctx, resServerInternalID, resInternalID, handle)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *int, string) error); ok {
		r1 = returnFunc(ctx, resServerInternalID, resInternalID, handle)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckActionHandleExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckActionHandleExists'
type resourceStoreInterfaceMock_CheckActionHandleExists_Call struct {
	*mock.Call
}

// CheckActionHandleExists is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
//   - resInternalID *int
//   - handle string
func (_e *resourceStoreInterfaceMock_Expecter) CheckActionHandleExists(ctx interface{}, resServerInternalID interface{}, resInternalID interface{}, handle interface{}) *resourceStoreInterfaceMock_CheckActionHandleExists_Call {
	return &resourceStoreInterfaceMock_CheckActionHandleExists_Call{Call: _e.mock.On("CheckActionHandleExists", ctx, resServerInternalID, resInternalID, handle)}
}

func (_c *resourceStoreInterfaceMock_CheckActionHandleExists_Call) Run(run func(ctx context.Context, resServerInternalID int, resInternalID *int, handle string)) *resourceStoreInterfaceMock_CheckActionHandleExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckActionHandleExists_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckActionHandleExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckActionHandleExists_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int, resInternalID *int, handle string) (bool, error)) *resourceStoreInterfaceMock_CheckActionHandleExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckCircularDependency provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckCircularDependency(ctx context.Context, resourceID string, newParentID string) (bool, error) {
	ret := _mock.Called(ctx, resourceID, newParentID)

	if len(ret) == 0 {
		panic("no return value specified for CheckCircularDependency")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, resourceID, newParentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, resourceID, newParentID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceID, newParentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckCircularDependency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckCircularDependency'
type resourceStoreInterfaceMock_CheckCircularDependency_Call struct {
	*mock.Call
}

// CheckCircularDependency is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
//   - newParentID string
func (_e *resourceStoreInterfaceMock_Expecter) CheckCircularDependency(ctx interface{}, resourceID interface{}, newParentID interface{}) *resourceStoreInterfaceMock_CheckCircularDependency_Call {
	return &resourceStoreInterfaceMock_CheckCircularDependency_Call{Call: _e.mock.On("CheckCircularDependency", ctx, resourceID, newParentID)}
}

func (_c *resourceStoreInterfaceMock_CheckCircularDependency_Call) Run(run func(ctx context.Context, resourceID string, newParentID string)) *resourceStoreInterfaceMock_CheckCircularDependency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckCircularDependency_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckCircularDependency_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckCircularDependency_Call) RunAndReturn(run func(ctx context.Context, resourceID string, newParentID string) (bool, error)) *resourceStoreInterfaceMock_CheckCircularDependency_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceHandleExists provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceHandleExists(ctx context.Context, resServerInternalID int, handle string, parentInternalID *int) (bool, error) {
	ret := _mock.Called(ctx, resServerInternalID, handle, parentInternalID)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceHandleExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, *int) (bool, error)); ok {
		return returnFunc(ctx, resServerInternalID, handle, parentInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, *int) bool); ok {
		r0 = returnFunc(ctx, resServerInternalID, handle, parentInternalID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string, *int) error); ok {
		r1 = returnFunc(ctx, resServerInternalID, handle, parentInternalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceHandleExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceHandleExists'
type resourceStoreInterfaceMock_CheckResourceHandleExists_Call struct {
	*mock.Call
}

// CheckResourceHandleExists is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
//   - handle string
//   - parentInternalID *int
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceHandleExists(ctx interface{}, resServerInternalID interface{}, handle interface{}, parentInternalID interface{}) *resourceStoreInterfaceMock_CheckResourceHandleExists_Call {
	return &resourceStoreInterfaceMock_CheckResourceHandleExists_Call{Call: _e.mock.On("CheckResourceHandleExists", ctx, resServerInternalID, handle, parentInternalID)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceHandleExists_Call) Run(run func(ctx context.Context, resServerInternalID int, handle string, parentInternalID *int)) *resourceStoreInterfaceMock_CheckResourceHandleExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceHandleExists_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceHandleExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceHandleExists_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int, handle string, parentInternalID *int) (bool, error)) *resourceStoreInterfaceMock_CheckResourceHandleExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceHasDependencies provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceHasDependencies(ctx context.Context, resInternalID int) (bool, error) {
	ret := _mock.Called(ctx, resInternalID)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceHasDependencies")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, resInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, resInternalID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, resInternalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceHasDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceHasDependencies'
type resourceStoreInterfaceMock_CheckResourceHasDependencies_Call struct {
	*mock.Call
}

// CheckResourceHasDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - resInternalID int
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceHasDependencies(ctx interface{}, resInternalID interface{}) *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call {
	return &resourceStoreInterfaceMock_CheckResourceHasDependencies_Call{Call: _e.mock.On("CheckResourceHasDependencies", ctx, resInternalID)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call) Run(run func(ctx context.Context, resInternalID int)) *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call) RunAndReturn(run func(ctx context.Context, resInternalID int) (bool, error)) *resourceStoreInterfaceMock_CheckResourceHasDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerHasDependencies provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerHasDependencies(ctx context.Context, resServerInternalID int) (bool, error) {
	ret := _mock.Called(ctx, resServerInternalID)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerHasDependencies")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, resServerInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, resServerInternalID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, resServerInternalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerHasDependencies'
type resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call struct {
	*mock.Call
}

// CheckResourceServerHasDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerHasDependencies(ctx interface{}, resServerInternalID interface{}) *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call{Call: _e.mock.On("CheckResourceServerHasDependencies", ctx, resServerInternalID)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call) Run(run func(ctx context.Context, resServerInternalID int)) *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int) (bool, error)) *resourceStoreInterfaceMock_CheckResourceServerHasDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerIdentifierExists provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerIdentifierExists(ctx context.Context, identifier string) (bool, error) {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerIdentifierExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, identifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerIdentifierExists'
type resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call struct {
	*mock.Call
}

// CheckResourceServerIdentifierExists is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerIdentifierExists(ctx interface{}, identifier interface{}) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call{Call: _e.mock.On("CheckResourceServerIdentifierExists", ctx, identifier)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call) Run(run func(ctx context.Context, identifier string)) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call) RunAndReturn(run func(ctx context.Context, identifier string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceServerIdentifierExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckResourceServerNameExists provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CheckResourceServerNameExists(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceServerNameExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_CheckResourceServerNameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceServerNameExists'
type resourceStoreInterfaceMock_CheckResourceServerNameExists_Call struct {
	*mock.Call
}

// CheckResourceServerNameExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *resourceStoreInterfaceMock_Expecter) CheckResourceServerNameExists(ctx interface{}, name interface{}) *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call {
	return &resourceStoreInterfaceMock_CheckResourceServerNameExists_Call{Call: _e.mock.On("CheckResourceServerNameExists", ctx, name)}
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call) Run(run func(ctx context.Context, name string)) *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call) Return(b bool, err error) *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *resourceStoreInterfaceMock_CheckResourceServerNameExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAction provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CreateAction(ctx context.Context, uuid string, resServerInternalID int, resInternalID *int, action Action) error {
	ret := _mock.Called(ctx, uuid, resServerInternalID, resInternalID, action)

	if len(ret) == 0 {
		panic("no return value specified for CreateAction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int, Action) error); ok {
		r0 = returnFunc(ctx, uuid, resServerInternalID, resInternalID, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_CreateAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAction'
type resourceStoreInterfaceMock_CreateAction_Call struct {
	*mock.Call
}

// CreateAction is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - resServerInternalID int
//   - resInternalID *int
//   - action Action
func (_e *resourceStoreInterfaceMock_Expecter) CreateAction(ctx interface{}, uuid interface{}, resServerInternalID interface{}, resInternalID interface{}, action interface{}) *resourceStoreInterfaceMock_CreateAction_Call {
	return &resourceStoreInterfaceMock_CreateAction_Call{Call: _e.mock.On("CreateAction", ctx, uuid, resServerInternalID, resInternalID, action)}
}

func (_c *resourceStoreInterfaceMock_CreateAction_Call) Run(run func(ctx context.Context, uuid string, resServerInternalID int, resInternalID *int, action Action)) *resourceStoreInterfaceMock_CreateAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 Action
		if args[4] != nil {
			arg4 = args[4].(Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateAction_Call) Return(err error) *resourceStoreInterfaceMock_CreateAction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateAction_Call) RunAndReturn(run func(ctx context.Context, uuid string, resServerInternalID int, resInternalID *int, action Action) error) *resourceStoreInterfaceMock_CreateAction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CreateResource(ctx context.Context, uuid string, resServerInternalID int, parentInternalID *int, res Resource) error {
	ret := _mock.Called(ctx, uuid, resServerInternalID, parentInternalID, res)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int, Resource) error); ok {
		r0 = returnFunc(ctx, uuid, resServerInternalID, parentInternalID, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type resourceStoreInterfaceMock_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - resServerInternalID int
//   - parentInternalID *int
//   - res Resource
func (_e *resourceStoreInterfaceMock_Expecter) CreateResource(ctx interface{}, uuid interface{}, resServerInternalID interface{}, parentInternalID interface{}, res interface{}) *resourceStoreInterfaceMock_CreateResource_Call {
	return &resourceStoreInterfaceMock_CreateResource_Call{Call: _e.mock.On("CreateResource", ctx, uuid, resServerInternalID, parentInternalID, res)}
}

func (_c *resourceStoreInterfaceMock_CreateResource_Call) Run(run func(ctx context.Context, uuid string, resServerInternalID int, parentInternalID *int, res Resource)) *resourceStoreInterfaceMock_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 Resource
		if args[4] != nil {
			arg4 = args[4].(Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateResource_Call) Return(err error) *resourceStoreInterfaceMock_CreateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateResource_Call) RunAndReturn(run func(ctx context.Context, uuid string, resServerInternalID int, parentInternalID *int, res Resource) error) *resourceStoreInterfaceMock_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) CreateResourceServer(ctx context.Context, id string, rs ResourceServer) error {
	ret := _mock.Called(ctx, id, rs)

	if len(ret) == 0 {
		panic("no return value specified for CreateResourceServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ResourceServer) error); ok {
		r0 = returnFunc(ctx, id, rs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_CreateResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResourceServer'
type resourceStoreInterfaceMock_CreateResourceServer_Call struct {
	*mock.Call
}

// CreateResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - rs ResourceServer
func (_e *resourceStoreInterfaceMock_Expecter) CreateResourceServer(ctx interface{}, id interface{}, rs interface{}) *resourceStoreInterfaceMock_CreateResourceServer_Call {
	return &resourceStoreInterfaceMock_CreateResourceServer_Call{Call: _e.mock.On("CreateResourceServer", ctx, id, rs)}
}

func (_c *resourceStoreInterfaceMock_CreateResourceServer_Call) Run(run func(ctx context.Context, id string, rs ResourceServer)) *resourceStoreInterfaceMock_CreateResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ResourceServer
		if args[2] != nil {
			arg2 = args[2].(ResourceServer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateResourceServer_Call) Return(err error) *resourceStoreInterfaceMock_CreateResourceServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_CreateResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string, rs ResourceServer) error) *resourceStoreInterfaceMock_CreateResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAction provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) DeleteAction(ctx context.Context, id string, resServerInternalID int, resInternalID *int) error {
	ret := _mock.Called(ctx, id, resServerInternalID, resInternalID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int) error); ok {
		r0 = returnFunc(ctx, id, resServerInternalID, resInternalID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_DeleteAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAction'
type resourceStoreInterfaceMock_DeleteAction_Call struct {
	*mock.Call
}

// DeleteAction is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - resServerInternalID int
//   - resInternalID *int
func (_e *resourceStoreInterfaceMock_Expecter) DeleteAction(ctx interface{}, id interface{}, resServerInternalID interface{}, resInternalID interface{}) *resourceStoreInterfaceMock_DeleteAction_Call {
	return &resourceStoreInterfaceMock_DeleteAction_Call{Call: _e.mock.On("DeleteAction", ctx, id, resServerInternalID, resInternalID)}
}

func (_c *resourceStoreInterfaceMock_DeleteAction_Call) Run(run func(ctx context.Context, id string, resServerInternalID int, resInternalID *int)) *resourceStoreInterfaceMock_DeleteAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteAction_Call) Return(err error) *resourceStoreInterfaceMock_DeleteAction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteAction_Call) RunAndReturn(run func(ctx context.Context, id string, resServerInternalID int, resInternalID *int) error) *resourceStoreInterfaceMock_DeleteAction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) DeleteResource(ctx context.Context, id string, resServerInternalID int) error {
	ret := _mock.Called(ctx, id, resServerInternalID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, id, resServerInternalID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type resourceStoreInterfaceMock_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - resServerInternalID int
func (_e *resourceStoreInterfaceMock_Expecter) DeleteResource(ctx interface{}, id interface{}, resServerInternalID interface{}) *resourceStoreInterfaceMock_DeleteResource_Call {
	return &resourceStoreInterfaceMock_DeleteResource_Call{Call: _e.mock.On("DeleteResource", ctx, id, resServerInternalID)}
}

func (_c *resourceStoreInterfaceMock_DeleteResource_Call) Run(run func(ctx context.Context, id string, resServerInternalID int)) *resourceStoreInterfaceMock_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteResource_Call) Return(err error) *resourceStoreInterfaceMock_DeleteResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteResource_Call) RunAndReturn(run func(ctx context.Context, id string, resServerInternalID int) error) *resourceStoreInterfaceMock_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) DeleteResourceServer(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResourceServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_DeleteResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResourceServer'
type resourceStoreInterfaceMock_DeleteResourceServer_Call struct {
	*mock.Call
}

// DeleteResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *resourceStoreInterfaceMock_Expecter) DeleteResourceServer(ctx interface{}, id interface{}) *resourceStoreInterfaceMock_DeleteResourceServer_Call {
	return &resourceStoreInterfaceMock_DeleteResourceServer_Call{Call: _e.mock.On("DeleteResourceServer", ctx, id)}
}

func (_c *resourceStoreInterfaceMock_DeleteResourceServer_Call) Run(run func(ctx context.Context, id string)) *resourceStoreInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteResourceServer_Call) Return(err error) *resourceStoreInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_DeleteResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string) error) *resourceStoreInterfaceMock_DeleteResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAction provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetAction(ctx context.Context, id string, resServerInternalID int, resInternalID *int) (Action, error) {
	ret := _mock.Called(ctx, id, resServerInternalID, resInternalID)

	if len(ret) == 0 {
		panic("no return value specified for GetAction")
	}

	var r0 Action
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int) (Action, error)); ok {
		return returnFunc(ctx, id, resServerInternalID, resInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int) Action); ok {
		r0 = returnFunc(ctx, id, resServerInternalID, resInternalID)
	} else {
		r0 = ret.Get(0).(Action)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, *int) error); ok {
		r1 = returnFunc(ctx, id, resServerInternalID, resInternalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAction'
type resourceStoreInterfaceMock_GetAction_Call struct {
	*mock.Call
}

// GetAction is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - resServerInternalID int
//   - resInternalID *int
func (_e *resourceStoreInterfaceMock_Expecter) GetAction(ctx interface{}, id interface{}, resServerInternalID interface{}, resInternalID interface{}) *resourceStoreInterfaceMock_GetAction_Call {
	return &resourceStoreInterfaceMock_GetAction_Call{Call: _e.mock.On("GetAction", ctx, id, resServerInternalID, resInternalID)}
}

func (_c *resourceStoreInterfaceMock_GetAction_Call) Run(run func(ctx context.Context, id string, resServerInternalID int, resInternalID *int)) *resourceStoreInterfaceMock_GetAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetAction_Call) Return(action Action, err error) *resourceStoreInterfaceMock_GetAction_Call {
	_c.Call.Return(action, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetAction_Call) RunAndReturn(run func(ctx context.Context, id string, resServerInternalID int, resInternalID *int) (Action, error)) *resourceStoreInterfaceMock_GetAction_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionList provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetActionList(ctx context.Context, resServerInternalID int, resInternalID *int, limit int, offset int) ([]Action, error) {
	ret := _mock.Called(ctx, resServerInternalID, resInternalID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetActionList")
	}

	var r0 []Action
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int, int, int) ([]Action, error)); ok {
		return returnFunc(ctx, resServerInternalID, resInternalID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int, int, int) []Action); ok {
		r0 = returnFunc(ctx, resServerInternalID, resInternalID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *int, int, int) error); ok {
		r1 = returnFunc(ctx, resServerInternalID, resInternalID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetActionList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionList'
type resourceStoreInterfaceMock_GetActionList_Call struct {
	*mock.Call
}

// GetActionList is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
//   - resInternalID *int
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetActionList(ctx interface{}, resServerInternalID interface{}, resInternalID interface{}, limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetActionList_Call {
	return &resourceStoreInterfaceMock_GetActionList_Call{Call: _e.mock.On("GetActionList", ctx, resServerInternalID, resInternalID, limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetActionList_Call) Run(run func(ctx context.Context, resServerInternalID int, resInternalID *int, limit int, offset int)) *resourceStoreInterfaceMock_GetActionList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionList_Call) Return(actions []Action, err error) *resourceStoreInterfaceMock_GetActionList_Call {
	_c.Call.Return(actions, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionList_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int, resInternalID *int, limit int, offset int) ([]Action, error)) *resourceStoreInterfaceMock_GetActionList_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionListCount provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetActionListCount(ctx context.Context, resServerInternalID int, resInternalID *int) (int, error) {
	ret := _mock.Called(ctx, resServerInternalID, resInternalID)

	if len(ret) == 0 {
		panic("no return value specified for GetActionListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int) (int, error)); ok {
		return returnFunc(ctx, resServerInternalID, resInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int) int); ok {
		r0 = returnFunc(ctx, resServerInternalID, resInternalID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *int) error); ok {
		r1 = returnFunc(ctx, resServerInternalID, resInternalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetActionListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionListCount'
type resourceStoreInterfaceMock_GetActionListCount_Call struct {
	*mock.Call
}

// GetActionListCount is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
//   - resInternalID *int
func (_e *resourceStoreInterfaceMock_Expecter) GetActionListCount(ctx interface{}, resServerInternalID interface{}, resInternalID interface{}) *resourceStoreInterfaceMock_GetActionListCount_Call {
	return &resourceStoreInterfaceMock_GetActionListCount_Call{Call: _e.mock.On("GetActionListCount", ctx, resServerInternalID, resInternalID)}
}

func (_c *resourceStoreInterfaceMock_GetActionListCount_Call) Run(run func(ctx context.Context, resServerInternalID int, resInternalID *int)) *resourceStoreInterfaceMock_GetActionListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListCount_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetActionListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetActionListCount_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int, resInternalID *int) (int, error)) *resourceStoreInterfaceMock_GetActionListCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResource(ctx context.Context, id string, resServerInternalID int) (int, Resource, error) {
	ret := _mock.Called(ctx, id, resServerInternalID)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 int
	var r1 Resource
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (int, Resource, error)); ok {
		return returnFunc(ctx, id, resServerInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) int); ok {
		r0 = returnFunc(ctx, id, resServerInternalID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) Resource); ok {
		r1 = returnFunc(ctx, id, resServerInternalID)
	} else {
		r1 = ret.Get(1).(Resource)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int) error); ok {
		r2 = returnFunc(ctx, id, resServerInternalID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// resourceStoreInterfaceMock_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type resourceStoreInterfaceMock_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - resServerInternalID int
func (_e *resourceStoreInterfaceMock_Expecter) GetResource(ctx interface{}, id interface{}, resServerInternalID interface{}) *resourceStoreInterfaceMock_GetResource_Call {
	return &resourceStoreInterfaceMock_GetResource_Call{Call: _e.mock.On("GetResource", ctx, id, resServerInternalID)}
}

func (_c *resourceStoreInterfaceMock_GetResource_Call) Run(run func(ctx context.Context, id string, resServerInternalID int)) *resourceStoreInterfaceMock_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResource_Call) Return(n int, resource Resource, err error) *resourceStoreInterfaceMock_GetResource_Call {
	_c.Call.Return(n, resource, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResource_Call) RunAndReturn(run func(ctx context.Context, id string, resServerInternalID int) (int, Resource, error)) *resourceStoreInterfaceMock_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceList provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceList(ctx context.Context, resServerInternalID int, limit int, offset int) ([]Resource, error) {
	ret := _mock.Called(ctx, resServerInternalID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceList")
	}

	var r0 []Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) ([]Resource, error)); ok {
		return returnFunc(ctx, resServerInternalID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) []Resource); ok {
		r0 = returnFunc(ctx, resServerInternalID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = returnFunc(ctx, resServerInternalID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceList'
type resourceStoreInterfaceMock_GetResourceList_Call struct {
	*mock.Call
}

// GetResourceList is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceList(ctx interface{}, resServerInternalID interface{}, limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetResourceList_Call {
	return &resourceStoreInterfaceMock_GetResourceList_Call{Call: _e.mock.On("GetResourceList", ctx, resServerInternalID, limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetResourceList_Call) Run(run func(ctx context.Context, resServerInternalID int, limit int, offset int)) *resourceStoreInterfaceMock_GetResourceList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceList_Call) Return(resources []Resource, err error) *resourceStoreInterfaceMock_GetResourceList_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceList_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int, limit int, offset int) ([]Resource, error)) *resourceStoreInterfaceMock_GetResourceList_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceListByParent provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceListByParent(ctx context.Context, resServerInternalID int, parentInternalID *int, limit int, offset int) ([]Resource, error) {
	ret := _mock.Called(ctx, resServerInternalID, parentInternalID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceListByParent")
	}

	var r0 []Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int, int, int) ([]Resource, error)); ok {
		return returnFunc(ctx, resServerInternalID, parentInternalID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int, int, int) []Resource); ok {
		r0 = returnFunc(ctx, resServerInternalID, parentInternalID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *int, int, int) error); ok {
		r1 = returnFunc(ctx, resServerInternalID, parentInternalID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceListByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceListByParent'
type resourceStoreInterfaceMock_GetResourceListByParent_Call struct {
	*mock.Call
}

// GetResourceListByParent is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
//   - parentInternalID *int
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceListByParent(ctx interface{}, resServerInternalID interface{}, parentInternalID interface{}, limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetResourceListByParent_Call {
	return &resourceStoreInterfaceMock_GetResourceListByParent_Call{Call: _e.mock.On("GetResourceListByParent", ctx, resServerInternalID, parentInternalID, limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetResourceListByParent_Call) Run(run func(ctx context.Context, resServerInternalID int, parentInternalID *int, limit int, offset int)) *resourceStoreInterfaceMock_GetResourceListByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListByParent_Call) Return(resources []Resource, err error) *resourceStoreInterfaceMock_GetResourceListByParent_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListByParent_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int, parentInternalID *int, limit int, offset int) ([]Resource, error)) *resourceStoreInterfaceMock_GetResourceListByParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceListCount provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceListCount(ctx context.Context, resServerInternalID int) (int, error) {
	ret := _mock.Called(ctx, resServerInternalID)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, resServerInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, resServerInternalID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, resServerInternalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceListCount'
type resourceStoreInterfaceMock_GetResourceListCount_Call struct {
	*mock.Call
}

// GetResourceListCount is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceListCount(ctx interface{}, resServerInternalID interface{}) *resourceStoreInterfaceMock_GetResourceListCount_Call {
	return &resourceStoreInterfaceMock_GetResourceListCount_Call{Call: _e.mock.On("GetResourceListCount", ctx, resServerInternalID)}
}

func (_c *resourceStoreInterfaceMock_GetResourceListCount_Call) Run(run func(ctx context.Context, resServerInternalID int)) *resourceStoreInterfaceMock_GetResourceListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListCount_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetResourceListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListCount_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int) (int, error)) *resourceStoreInterfaceMock_GetResourceListCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceListCountByParent provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceListCountByParent(ctx context.Context, resServerInternalID int, parentInternalID *int) (int, error) {
	ret := _mock.Called(ctx, resServerInternalID, parentInternalID)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceListCountByParent")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int) (int, error)); ok {
		return returnFunc(ctx, resServerInternalID, parentInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *int) int); ok {
		r0 = returnFunc(ctx, resServerInternalID, parentInternalID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *int) error); ok {
		r1 = returnFunc(ctx, resServerInternalID, parentInternalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceListCountByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceListCountByParent'
type resourceStoreInterfaceMock_GetResourceListCountByParent_Call struct {
	*mock.Call
}

// GetResourceListCountByParent is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
//   - parentInternalID *int
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceListCountByParent(ctx interface{}, resServerInternalID interface{}, parentInternalID interface{}) *resourceStoreInterfaceMock_GetResourceListCountByParent_Call {
	return &resourceStoreInterfaceMock_GetResourceListCountByParent_Call{Call: _e.mock.On("GetResourceListCountByParent", ctx, resServerInternalID, parentInternalID)}
}

func (_c *resourceStoreInterfaceMock_GetResourceListCountByParent_Call) Run(run func(ctx context.Context, resServerInternalID int, parentInternalID *int)) *resourceStoreInterfaceMock_GetResourceListCountByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListCountByParent_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetResourceListCountByParent_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceListCountByParent_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int, parentInternalID *int) (int, error)) *resourceStoreInterfaceMock_GetResourceListCountByParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceServer(ctx context.Context, id string) (int, ResourceServer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServer")
	}

	var r0 int
	var r1 ResourceServer
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, ResourceServer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) ResourceServer); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(ResourceServer)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// resourceStoreInterfaceMock_GetResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServer'
type resourceStoreInterfaceMock_GetResourceServer_Call struct {
	*mock.Call
}

// GetResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceServer(ctx interface{}, id interface{}) *resourceStoreInterfaceMock_GetResourceServer_Call {
	return &resourceStoreInterfaceMock_GetResourceServer_Call{Call: _e.mock.On("GetResourceServer", ctx, id)}
}

func (_c *resourceStoreInterfaceMock_GetResourceServer_Call) Run(run func(ctx context.Context, id string)) *resourceStoreInterfaceMock_GetResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServer_Call) Return(n int, resourceServer ResourceServer, err error) *resourceStoreInterfaceMock_GetResourceServer_Call {
	_c.Call.Return(n, resourceServer, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string) (int, ResourceServer, error)) *resourceStoreInterfaceMock_GetResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServerList provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceServerList(ctx context.Context, limit int, offset int) ([]ResourceServer, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerList")
	}

	var r0 []ResourceServer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]ResourceServer, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []ResourceServer); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ResourceServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceServerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerList'
type resourceStoreInterfaceMock_GetResourceServerList_Call struct {
	*mock.Call
}

// GetResourceServerList is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceServerList(ctx interface{}, limit interface{}, offset interface{}) *resourceStoreInterfaceMock_GetResourceServerList_Call {
	return &resourceStoreInterfaceMock_GetResourceServerList_Call{Call: _e.mock.On("GetResourceServerList", ctx, limit, offset)}
}

func (_c *resourceStoreInterfaceMock_GetResourceServerList_Call) Run(run func(ctx context.Context, limit int, offset int)) *resourceStoreInterfaceMock_GetResourceServerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServerList_Call) Return(resourceServers []ResourceServer, err error) *resourceStoreInterfaceMock_GetResourceServerList_Call {
	_c.Call.Return(resourceServers, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServerList_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]ResourceServer, error)) *resourceStoreInterfaceMock_GetResourceServerList_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceServerListCount provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) GetResourceServerListCount(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_GetResourceServerListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerListCount'
type resourceStoreInterfaceMock_GetResourceServerListCount_Call struct {
	*mock.Call
}

// GetResourceServerListCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *resourceStoreInterfaceMock_Expecter) GetResourceServerListCount(ctx interface{}) *resourceStoreInterfaceMock_GetResourceServerListCount_Call {
	return &resourceStoreInterfaceMock_GetResourceServerListCount_Call{Call: _e.mock.On("GetResourceServerListCount", ctx)}
}

func (_c *resourceStoreInterfaceMock_GetResourceServerListCount_Call) Run(run func(ctx context.Context)) *resourceStoreInterfaceMock_GetResourceServerListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServerListCount_Call) Return(n int, err error) *resourceStoreInterfaceMock_GetResourceServerListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_GetResourceServerListCount_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *resourceStoreInterfaceMock_GetResourceServerListCount_Call {
	_c.Call.Return(run)
	return _c
}

// IsActionExist provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) IsActionExist(ctx context.Context, id string, resServerInternalID int, resInternalID *int) (bool, error) {
	ret := _mock.Called(ctx, id, resServerInternalID, resInternalID)

	if len(ret) == 0 {
		panic("no return value specified for IsActionExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int) (bool, error)); ok {
		return returnFunc(ctx, id, resServerInternalID, resInternalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int) bool); ok {
		r0 = returnFunc(ctx, id, resServerInternalID, resInternalID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, *int) error); ok {
		r1 = returnFunc(ctx, id, resServerInternalID, resInternalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_IsActionExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActionExist'
type resourceStoreInterfaceMock_IsActionExist_Call struct {
	*mock.Call
}

// IsActionExist is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - resServerInternalID int
//   - resInternalID *int
func (_e *resourceStoreInterfaceMock_Expecter) IsActionExist(ctx interface{}, id interface{}, resServerInternalID interface{}, resInternalID interface{}) *resourceStoreInterfaceMock_IsActionExist_Call {
	return &resourceStoreInterfaceMock_IsActionExist_Call{Call: _e.mock.On("IsActionExist", ctx, id, resServerInternalID, resInternalID)}
}

func (_c *resourceStoreInterfaceMock_IsActionExist_Call) Run(run func(ctx context.Context, id string, resServerInternalID int, resInternalID *int)) *resourceStoreInterfaceMock_IsActionExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_IsActionExist_Call) Return(b bool, err error) *resourceStoreInterfaceMock_IsActionExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_IsActionExist_Call) RunAndReturn(run func(ctx context.Context, id string, resServerInternalID int, resInternalID *int) (bool, error)) *resourceStoreInterfaceMock_IsActionExist_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAction provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) UpdateAction(ctx context.Context, id string, resServerInternalID int, resInternalID *int, action Action) error {
	ret := _mock.Called(ctx, id, resServerInternalID, resInternalID, action)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, *int, Action) error); ok {
		r0 = returnFunc(ctx, id, resServerInternalID, resInternalID, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_UpdateAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAction'
type resourceStoreInterfaceMock_UpdateAction_Call struct {
	*mock.Call
}

// UpdateAction is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - resServerInternalID int
//   - resInternalID *int
//   - action Action
func (_e *resourceStoreInterfaceMock_Expecter) UpdateAction(ctx interface{}, id interface{}, resServerInternalID interface{}, resInternalID interface{}, action interface{}) *resourceStoreInterfaceMock_UpdateAction_Call {
	return &resourceStoreInterfaceMock_UpdateAction_Call{Call: _e.mock.On("UpdateAction", ctx, id, resServerInternalID, resInternalID, action)}
}

func (_c *resourceStoreInterfaceMock_UpdateAction_Call) Run(run func(ctx context.Context, id string, resServerInternalID int, resInternalID *int, action Action)) *resourceStoreInterfaceMock_UpdateAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 Action
		if args[4] != nil {
			arg4 = args[4].(Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateAction_Call) Return(err error) *resourceStoreInterfaceMock_UpdateAction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateAction_Call) RunAndReturn(run func(ctx context.Context, id string, resServerInternalID int, resInternalID *int, action Action) error) *resourceStoreInterfaceMock_UpdateAction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) UpdateResource(ctx context.Context, id string, resServerInternalID int, res Resource) error {
	ret := _mock.Called(ctx, id, resServerInternalID, res)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, Resource) error); ok {
		r0 = returnFunc(ctx, id, resServerInternalID, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type resourceStoreInterfaceMock_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - resServerInternalID int
//   - res Resource
func (_e *resourceStoreInterfaceMock_Expecter) UpdateResource(ctx interface{}, id interface{}, resServerInternalID interface{}, res interface{}) *resourceStoreInterfaceMock_UpdateResource_Call {
	return &resourceStoreInterfaceMock_UpdateResource_Call{Call: _e.mock.On("UpdateResource", ctx, id, resServerInternalID, res)}
}

func (_c *resourceStoreInterfaceMock_UpdateResource_Call) Run(run func(ctx context.Context, id string, resServerInternalID int, res Resource)) *resourceStoreInterfaceMock_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 Resource
		if args[3] != nil {
			arg3 = args[3].(Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateResource_Call) Return(err error) *resourceStoreInterfaceMock_UpdateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateResource_Call) RunAndReturn(run func(ctx context.Context, id string, resServerInternalID int, res Resource) error) *resourceStoreInterfaceMock_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceServer provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) UpdateResourceServer(ctx context.Context, id string, rs ResourceServer) error {
	ret := _mock.Called(ctx, id, rs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ResourceServer) error); ok {
		r0 = returnFunc(ctx, id, rs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// resourceStoreInterfaceMock_UpdateResourceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceServer'
type resourceStoreInterfaceMock_UpdateResourceServer_Call struct {
	*mock.Call
}

// UpdateResourceServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - rs ResourceServer
func (_e *resourceStoreInterfaceMock_Expecter) UpdateResourceServer(ctx interface{}, id interface{}, rs interface{}) *resourceStoreInterfaceMock_UpdateResourceServer_Call {
	return &resourceStoreInterfaceMock_UpdateResourceServer_Call{Call: _e.mock.On("UpdateResourceServer", ctx, id, rs)}
}

func (_c *resourceStoreInterfaceMock_UpdateResourceServer_Call) Run(run func(ctx context.Context, id string, rs ResourceServer)) *resourceStoreInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ResourceServer
		if args[2] != nil {
			arg2 = args[2].(ResourceServer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateResourceServer_Call) Return(err error) *resourceStoreInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *resourceStoreInterfaceMock_UpdateResourceServer_Call) RunAndReturn(run func(ctx context.Context, id string, rs ResourceServer) error) *resourceStoreInterfaceMock_UpdateResourceServer_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePermissions provides a mock function for the type resourceStoreInterfaceMock
func (_mock *resourceStoreInterfaceMock) ValidatePermissions(ctx context.Context, resServerInternalID int, permissions []string) ([]string, error) {
	ret := _mock.Called(ctx, resServerInternalID, permissions)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []string) ([]string, error)); ok {
		return returnFunc(ctx, resServerInternalID, permissions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []string) []string); ok {
		r0 = returnFunc(ctx, resServerInternalID, permissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []string) error); ok {
		r1 = returnFunc(ctx, resServerInternalID, permissions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// resourceStoreInterfaceMock_ValidatePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePermissions'
type resourceStoreInterfaceMock_ValidatePermissions_Call struct {
	*mock.Call
}

// ValidatePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - resServerInternalID int
//   - permissions []string
func (_e *resourceStoreInterfaceMock_Expecter) ValidatePermissions(ctx interface{}, resServerInternalID interface{}, permissions interface{}) *resourceStoreInterfaceMock_ValidatePermissions_Call {
	return &resourceStoreInterfaceMock_ValidatePermissions_Call{Call: _e.mock.On("ValidatePermissions", ctx, resServerInternalID, permissions)}
}

func (_c *resourceStoreInterfaceMock_ValidatePermissions_Call) Run(run func(ctx context.Context, resServerInternalID int, permissions []string)) *resourceStoreInterfaceMock_ValidatePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *resourceStoreInterfaceMock_ValidatePermissions_Call) Return(strings []string, err error) *resourceStoreInterfaceMock_ValidatePermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *resourceStoreInterfaceMock_ValidatePermissions_Call) RunAndReturn(run func(ctx context.Context, resServerInternalID int, permissions []string) ([]string, error)) *resourceStoreInterfaceMock_ValidatePermissions_Call {
	_c.Call.Return(run)
	return _c
}
