// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authz

import (
	mock "github.com/stretchr/testify/mock"
)

// newAuthorizationRequestStoreInterfaceMock creates a new instance of authorizationRequestStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newAuthorizationRequestStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *authorizationRequestStoreInterfaceMock {
	mock := &authorizationRequestStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// authorizationRequestStoreInterfaceMock is an autogenerated mock type for the authorizationRequestStoreInterface type
type authorizationRequestStoreInterfaceMock struct {
	mock.Mock
}

type authorizationRequestStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *authorizationRequestStoreInterfaceMock) EXPECT() *authorizationRequestStoreInterfaceMock_Expecter {
	return &authorizationRequestStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// AddRequest provides a mock function for the type authorizationRequestStoreInterfaceMock
func (_mock *authorizationRequestStoreInterfaceMock) AddRequest(value authRequestContext) (string, error) {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for AddRequest")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(authRequestContext) (string, error)); ok {
		return returnFunc(value)
	}
	if returnFunc, ok := ret.Get(0).(func(authRequestContext) string); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(authRequestContext) error); ok {
		r1 = returnFunc(value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// authorizationRequestStoreInterfaceMock_AddRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRequest'
type authorizationRequestStoreInterfaceMock_AddRequest_Call struct {
	*mock.Call
}

// AddRequest is a helper method to define mock.On call
//   - value authRequestContext
func (_e *authorizationRequestStoreInterfaceMock_Expecter) AddRequest(value interface{}) *authorizationRequestStoreInterfaceMock_AddRequest_Call {
	return &authorizationRequestStoreInterfaceMock_AddRequest_Call{Call: _e.mock.On("AddRequest", value)}
}

func (_c *authorizationRequestStoreInterfaceMock_AddRequest_Call) Run(run func(value authRequestContext)) *authorizationRequestStoreInterfaceMock_AddRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 authRequestContext
		if args[0] != nil {
			arg0 = args[0].(authRequestContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *authorizationRequestStoreInterfaceMock_AddRequest_Call) Return(s string, err error) *authorizationRequestStoreInterfaceMock_AddRequest_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *authorizationRequestStoreInterfaceMock_AddRequest_Call) RunAndReturn(run func(value authRequestContext) (string, error)) *authorizationRequestStoreInterfaceMock_AddRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ClearRequest provides a mock function for the type authorizationRequestStoreInterfaceMock
func (_mock *authorizationRequestStoreInterfaceMock) ClearRequest(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ClearRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// authorizationRequestStoreInterfaceMock_ClearRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearRequest'
type authorizationRequestStoreInterfaceMock_ClearRequest_Call struct {
	*mock.Call
}

// ClearRequest is a helper method to define mock.On call
//   - key string
func (_e *authorizationRequestStoreInterfaceMock_Expecter) ClearRequest(key interface{}) *authorizationRequestStoreInterfaceMock_ClearRequest_Call {
	return &authorizationRequestStoreInterfaceMock_ClearRequest_Call{Call: _e.mock.On("ClearRequest", key)}
}

func (_c *authorizationRequestStoreInterfaceMock_ClearRequest_Call) Run(run func(key string)) *authorizationRequestStoreInterfaceMock_ClearRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *authorizationRequestStoreInterfaceMock_ClearRequest_Call) Return(err error) *authorizationRequestStoreInterfaceMock_ClearRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *authorizationRequestStoreInterfaceMock_ClearRequest_Call) RunAndReturn(run func(key string) error) *authorizationRequestStoreInterfaceMock_ClearRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function for the type authorizationRequestStoreInterfaceMock
func (_mock *authorizationRequestStoreInterfaceMock) GetRequest(key string) (bool, authRequestContext, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 bool
	var r1 authRequestContext
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, authRequestContext, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) authRequestContext); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(authRequestContext)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// authorizationRequestStoreInterfaceMock_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type authorizationRequestStoreInterfaceMock_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - key string
func (_e *authorizationRequestStoreInterfaceMock_Expecter) GetRequest(key interface{}) *authorizationRequestStoreInterfaceMock_GetRequest_Call {
	return &authorizationRequestStoreInterfaceMock_GetRequest_Call{Call: _e.mock.On("GetRequest", key)}
}

func (_c *authorizationRequestStoreInterfaceMock_GetRequest_Call) Run(run func(key string)) *authorizationRequestStoreInterfaceMock_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *authorizationRequestStoreInterfaceMock_GetRequest_Call) Return(b bool, authRequestContextMoqParam authRequestContext, err error) *authorizationRequestStoreInterfaceMock_GetRequest_Call {
	_c.Call.Return(b, authRequestContextMoqParam, err)
	return _c
}

func (_c *authorizationRequestStoreInterfaceMock_GetRequest_Call) RunAndReturn(run func(key string) (bool, authRequestContext, error)) *authorizationRequestStoreInterfaceMock_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}
