// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package passkeymock

import (
	"context"

	"github.com/asgardeo/thunder/internal/authn/passkeyauthn"
	"github.com/asgardeo/thunder/internal/authnprovider/common"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewPasskeyAuthnServiceInterfaceMock creates a new instance of PasskeyAuthnServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasskeyAuthnServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasskeyAuthnServiceInterfaceMock {
	mock := &PasskeyAuthnServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasskeyAuthnServiceInterfaceMock is an autogenerated mock type for the PasskeyAuthnServiceInterface type
type PasskeyAuthnServiceInterfaceMock struct {
	mock.Mock
}

type PasskeyAuthnServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PasskeyAuthnServiceInterfaceMock) EXPECT() *PasskeyAuthnServiceInterfaceMock_Expecter {
	return &PasskeyAuthnServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// FinishAuthentication provides a mock function for the type PasskeyAuthnServiceInterfaceMock
func (_mock *PasskeyAuthnServiceInterfaceMock) FinishAuthentication(ctx context.Context, req *passkeyauthn.AuthenticationFinishRequest) (*common.AuthnResult, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FinishAuthentication")
	}

	var r0 *common.AuthnResult
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *passkeyauthn.AuthenticationFinishRequest) (*common.AuthnResult, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *passkeyauthn.AuthenticationFinishRequest) *common.AuthnResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.AuthnResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *passkeyauthn.AuthenticationFinishRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishAuthentication'
type PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call struct {
	*mock.Call
}

// FinishAuthentication is a helper method to define mock.On call
//   - ctx context.Context
//   - req *passkeyauthn.AuthenticationFinishRequest
func (_e *PasskeyAuthnServiceInterfaceMock_Expecter) FinishAuthentication(ctx interface{}, req interface{}) *PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call {
	return &PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call{Call: _e.mock.On("FinishAuthentication", ctx, req)}
}

func (_c *PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call) Run(run func(ctx context.Context, req *passkeyauthn.AuthenticationFinishRequest)) *PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *passkeyauthn.AuthenticationFinishRequest
		if args[1] != nil {
			arg1 = args[1].(*passkeyauthn.AuthenticationFinishRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call) Return(authnResult *common.AuthnResult, serviceError *serviceerror.ServiceError) *PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call {
	_c.Call.Return(authnResult, serviceError)
	return _c
}

func (_c *PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call) RunAndReturn(run func(ctx context.Context, req *passkeyauthn.AuthenticationFinishRequest) (*common.AuthnResult, *serviceerror.ServiceError)) *PasskeyAuthnServiceInterfaceMock_FinishAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// FinishRegistration provides a mock function for the type PasskeyAuthnServiceInterfaceMock
func (_mock *PasskeyAuthnServiceInterfaceMock) FinishRegistration(ctx context.Context, req *passkeyauthn.RegistrationFinishRequest) (*passkeyauthn.RegistrationFinishData, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FinishRegistration")
	}

	var r0 *passkeyauthn.RegistrationFinishData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *passkeyauthn.RegistrationFinishRequest) (*passkeyauthn.RegistrationFinishData, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *passkeyauthn.RegistrationFinishRequest) *passkeyauthn.RegistrationFinishData); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkeyauthn.RegistrationFinishData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *passkeyauthn.RegistrationFinishRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishRegistration'
type PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call struct {
	*mock.Call
}

// FinishRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - req *passkeyauthn.RegistrationFinishRequest
func (_e *PasskeyAuthnServiceInterfaceMock_Expecter) FinishRegistration(ctx interface{}, req interface{}) *PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call {
	return &PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call{Call: _e.mock.On("FinishRegistration", ctx, req)}
}

func (_c *PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call) Run(run func(ctx context.Context, req *passkeyauthn.RegistrationFinishRequest)) *PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *passkeyauthn.RegistrationFinishRequest
		if args[1] != nil {
			arg1 = args[1].(*passkeyauthn.RegistrationFinishRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call) Return(registrationFinishData *passkeyauthn.RegistrationFinishData, serviceError *serviceerror.ServiceError) *PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call {
	_c.Call.Return(registrationFinishData, serviceError)
	return _c
}

func (_c *PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call) RunAndReturn(run func(ctx context.Context, req *passkeyauthn.RegistrationFinishRequest) (*passkeyauthn.RegistrationFinishData, *serviceerror.ServiceError)) *PasskeyAuthnServiceInterfaceMock_FinishRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// StartAuthentication provides a mock function for the type PasskeyAuthnServiceInterfaceMock
func (_mock *PasskeyAuthnServiceInterfaceMock) StartAuthentication(ctx context.Context, req *passkeyauthn.AuthenticationStartRequest) (*passkeyauthn.AuthenticationStartData, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StartAuthentication")
	}

	var r0 *passkeyauthn.AuthenticationStartData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *passkeyauthn.AuthenticationStartRequest) (*passkeyauthn.AuthenticationStartData, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *passkeyauthn.AuthenticationStartRequest) *passkeyauthn.AuthenticationStartData); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkeyauthn.AuthenticationStartData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *passkeyauthn.AuthenticationStartRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAuthentication'
type PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call struct {
	*mock.Call
}

// StartAuthentication is a helper method to define mock.On call
//   - ctx context.Context
//   - req *passkeyauthn.AuthenticationStartRequest
func (_e *PasskeyAuthnServiceInterfaceMock_Expecter) StartAuthentication(ctx interface{}, req interface{}) *PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call {
	return &PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call{Call: _e.mock.On("StartAuthentication", ctx, req)}
}

func (_c *PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call) Run(run func(ctx context.Context, req *passkeyauthn.AuthenticationStartRequest)) *PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *passkeyauthn.AuthenticationStartRequest
		if args[1] != nil {
			arg1 = args[1].(*passkeyauthn.AuthenticationStartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call) Return(authenticationStartData *passkeyauthn.AuthenticationStartData, serviceError *serviceerror.ServiceError) *PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call {
	_c.Call.Return(authenticationStartData, serviceError)
	return _c
}

func (_c *PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call) RunAndReturn(run func(ctx context.Context, req *passkeyauthn.AuthenticationStartRequest) (*passkeyauthn.AuthenticationStartData, *serviceerror.ServiceError)) *PasskeyAuthnServiceInterfaceMock_StartAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// StartRegistration provides a mock function for the type PasskeyAuthnServiceInterfaceMock
func (_mock *PasskeyAuthnServiceInterfaceMock) StartRegistration(ctx context.Context, req *passkeyauthn.RegistrationStartRequest) (*passkeyauthn.RegistrationStartData, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StartRegistration")
	}

	var r0 *passkeyauthn.RegistrationStartData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *passkeyauthn.RegistrationStartRequest) (*passkeyauthn.RegistrationStartData, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *passkeyauthn.RegistrationStartRequest) *passkeyauthn.RegistrationStartData); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkeyauthn.RegistrationStartData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *passkeyauthn.RegistrationStartRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// PasskeyAuthnServiceInterfaceMock_StartRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartRegistration'
type PasskeyAuthnServiceInterfaceMock_StartRegistration_Call struct {
	*mock.Call
}

// StartRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - req *passkeyauthn.RegistrationStartRequest
func (_e *PasskeyAuthnServiceInterfaceMock_Expecter) StartRegistration(ctx interface{}, req interface{}) *PasskeyAuthnServiceInterfaceMock_StartRegistration_Call {
	return &PasskeyAuthnServiceInterfaceMock_StartRegistration_Call{Call: _e.mock.On("StartRegistration", ctx, req)}
}

func (_c *PasskeyAuthnServiceInterfaceMock_StartRegistration_Call) Run(run func(ctx context.Context, req *passkeyauthn.RegistrationStartRequest)) *PasskeyAuthnServiceInterfaceMock_StartRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *passkeyauthn.RegistrationStartRequest
		if args[1] != nil {
			arg1 = args[1].(*passkeyauthn.RegistrationStartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasskeyAuthnServiceInterfaceMock_StartRegistration_Call) Return(registrationStartData *passkeyauthn.RegistrationStartData, serviceError *serviceerror.ServiceError) *PasskeyAuthnServiceInterfaceMock_StartRegistration_Call {
	_c.Call.Return(registrationStartData, serviceError)
	return _c
}

func (_c *PasskeyAuthnServiceInterfaceMock_StartRegistration_Call) RunAndReturn(run func(ctx context.Context, req *passkeyauthn.RegistrationStartRequest) (*passkeyauthn.RegistrationStartData, *serviceerror.ServiceError)) *PasskeyAuthnServiceInterfaceMock_StartRegistration_Call {
	_c.Call.Return(run)
	return _c
}
