// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package granthandlersmock

import (
	"context"

	model0 "github.com/asgardeo/thunder/internal/application/model"
	"github.com/asgardeo/thunder/internal/oauth/oauth2/model"
	mock "github.com/stretchr/testify/mock"
)

// NewRefreshTokenGrantHandlerInterfaceMock creates a new instance of RefreshTokenGrantHandlerInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenGrantHandlerInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenGrantHandlerInterfaceMock {
	mock := &RefreshTokenGrantHandlerInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenGrantHandlerInterfaceMock is an autogenerated mock type for the RefreshTokenGrantHandlerInterface type
type RefreshTokenGrantHandlerInterfaceMock struct {
	mock.Mock
}

type RefreshTokenGrantHandlerInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenGrantHandlerInterfaceMock) EXPECT() *RefreshTokenGrantHandlerInterfaceMock_Expecter {
	return &RefreshTokenGrantHandlerInterfaceMock_Expecter{mock: &_m.Mock}
}

// HandleGrant provides a mock function for the type RefreshTokenGrantHandlerInterfaceMock
func (_mock *RefreshTokenGrantHandlerInterfaceMock) HandleGrant(ctx context.Context, tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO) (*model.TokenResponseDTO, *model.ErrorResponse) {
	ret := _mock.Called(ctx, tokenRequest, oauthApp)

	if len(ret) == 0 {
		panic("no return value specified for HandleGrant")
	}

	var r0 *model.TokenResponseDTO
	var r1 *model.ErrorResponse
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.TokenRequest, *model0.OAuthAppConfigProcessedDTO) (*model.TokenResponseDTO, *model.ErrorResponse)); ok {
		return returnFunc(ctx, tokenRequest, oauthApp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.TokenRequest, *model0.OAuthAppConfigProcessedDTO) *model.TokenResponseDTO); ok {
		r0 = returnFunc(ctx, tokenRequest, oauthApp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.TokenRequest, *model0.OAuthAppConfigProcessedDTO) *model.ErrorResponse); ok {
		r1 = returnFunc(ctx, tokenRequest, oauthApp)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorResponse)
		}
	}
	return r0, r1
}

// RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleGrant'
type RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call struct {
	*mock.Call
}

// HandleGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRequest *model.TokenRequest
//   - oauthApp *model0.OAuthAppConfigProcessedDTO
func (_e *RefreshTokenGrantHandlerInterfaceMock_Expecter) HandleGrant(ctx interface{}, tokenRequest interface{}, oauthApp interface{}) *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call {
	return &RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call{Call: _e.mock.On("HandleGrant", ctx, tokenRequest, oauthApp)}
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call) Run(run func(ctx context.Context, tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO)) *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.TokenRequest
		if args[1] != nil {
			arg1 = args[1].(*model.TokenRequest)
		}
		var arg2 *model0.OAuthAppConfigProcessedDTO
		if args[2] != nil {
			arg2 = args[2].(*model0.OAuthAppConfigProcessedDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call) Return(tokenResponseDTO *model.TokenResponseDTO, errorResponse *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call {
	_c.Call.Return(tokenResponseDTO, errorResponse)
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call) RunAndReturn(run func(ctx context.Context, tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO) (*model.TokenResponseDTO, *model.ErrorResponse)) *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefreshToken provides a mock function for the type RefreshTokenGrantHandlerInterfaceMock
func (_mock *RefreshTokenGrantHandlerInterfaceMock) IssueRefreshToken(ctx context.Context, tokenResponse *model.TokenResponseDTO, oauthApp *model0.OAuthAppConfigProcessedDTO, subject string, audience string, grantType string, scopes []string, claimsRequest *model.ClaimsRequest, claimsLocales string) *model.ErrorResponse {
	ret := _mock.Called(ctx, tokenResponse, oauthApp, subject, audience, grantType, scopes, claimsRequest, claimsLocales)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefreshToken")
	}

	var r0 *model.ErrorResponse
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.TokenResponseDTO, *model0.OAuthAppConfigProcessedDTO, string, string, string, []string, *model.ClaimsRequest, string) *model.ErrorResponse); ok {
		r0 = returnFunc(ctx, tokenResponse, oauthApp, subject, audience, grantType, scopes, claimsRequest, claimsLocales)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ErrorResponse)
		}
	}
	return r0
}

// RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenResponse *model.TokenResponseDTO
//   - oauthApp *model0.OAuthAppConfigProcessedDTO
//   - subject string
//   - audience string
//   - grantType string
//   - scopes []string
//   - claimsRequest *model.ClaimsRequest
//   - claimsLocales string
func (_e *RefreshTokenGrantHandlerInterfaceMock_Expecter) IssueRefreshToken(ctx interface{}, tokenResponse interface{}, oauthApp interface{}, subject interface{}, audience interface{}, grantType interface{}, scopes interface{}, claimsRequest interface{}, claimsLocales interface{}) *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call {
	return &RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken", ctx, tokenResponse, oauthApp, subject, audience, grantType, scopes, claimsRequest, claimsLocales)}
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call) Run(run func(ctx context.Context, tokenResponse *model.TokenResponseDTO, oauthApp *model0.OAuthAppConfigProcessedDTO, subject string, audience string, grantType string, scopes []string, claimsRequest *model.ClaimsRequest, claimsLocales string)) *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.TokenResponseDTO
		if args[1] != nil {
			arg1 = args[1].(*model.TokenResponseDTO)
		}
		var arg2 *model0.OAuthAppConfigProcessedDTO
		if args[2] != nil {
			arg2 = args[2].(*model0.OAuthAppConfigProcessedDTO)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 []string
		if args[6] != nil {
			arg6 = args[6].([]string)
		}
		var arg7 *model.ClaimsRequest
		if args[7] != nil {
			arg7 = args[7].(*model.ClaimsRequest)
		}
		var arg8 string
		if args[8] != nil {
			arg8 = args[8].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
		)
	})
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call) Return(errorResponse *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call {
	_c.Call.Return(errorResponse)
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenResponse *model.TokenResponseDTO, oauthApp *model0.OAuthAppConfigProcessedDTO, subject string, audience string, grantType string, scopes []string, claimsRequest *model.ClaimsRequest, claimsLocales string) *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateGrant provides a mock function for the type RefreshTokenGrantHandlerInterfaceMock
func (_mock *RefreshTokenGrantHandlerInterfaceMock) ValidateGrant(ctx context.Context, tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO) *model.ErrorResponse {
	ret := _mock.Called(ctx, tokenRequest, oauthApp)

	if len(ret) == 0 {
		panic("no return value specified for ValidateGrant")
	}

	var r0 *model.ErrorResponse
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.TokenRequest, *model0.OAuthAppConfigProcessedDTO) *model.ErrorResponse); ok {
		r0 = returnFunc(ctx, tokenRequest, oauthApp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ErrorResponse)
		}
	}
	return r0
}

// RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateGrant'
type RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call struct {
	*mock.Call
}

// ValidateGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenRequest *model.TokenRequest
//   - oauthApp *model0.OAuthAppConfigProcessedDTO
func (_e *RefreshTokenGrantHandlerInterfaceMock_Expecter) ValidateGrant(ctx interface{}, tokenRequest interface{}, oauthApp interface{}) *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call {
	return &RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call{Call: _e.mock.On("ValidateGrant", ctx, tokenRequest, oauthApp)}
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call) Run(run func(ctx context.Context, tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO)) *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.TokenRequest
		if args[1] != nil {
			arg1 = args[1].(*model.TokenRequest)
		}
		var arg2 *model0.OAuthAppConfigProcessedDTO
		if args[2] != nil {
			arg2 = args[2].(*model0.OAuthAppConfigProcessedDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call) Return(errorResponse *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call {
	_c.Call.Return(errorResponse)
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call) RunAndReturn(run func(ctx context.Context, tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO) *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call {
	_c.Call.Return(run)
	return _c
}
