// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package otpauthnmock

import (
	"context"

	"github.com/asgardeo/thunder/internal/authnprovider/common"
	common0 "github.com/asgardeo/thunder/internal/notification/common"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewOTPAuthnInterfaceMock creates a new instance of OTPAuthnInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTPAuthnInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTPAuthnInterfaceMock {
	mock := &OTPAuthnInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OTPAuthnInterfaceMock is an autogenerated mock type for the OTPAuthnInterface type
type OTPAuthnInterfaceMock struct {
	mock.Mock
}

type OTPAuthnInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OTPAuthnInterfaceMock) EXPECT() *OTPAuthnInterfaceMock_Expecter {
	return &OTPAuthnInterfaceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type OTPAuthnInterfaceMock
func (_mock *OTPAuthnInterfaceMock) Authenticate(ctx context.Context, sessionToken string, otp string) (*common.AuthnResult, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, sessionToken, otp)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *common.AuthnResult
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*common.AuthnResult, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, sessionToken, otp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *common.AuthnResult); ok {
		r0 = returnFunc(ctx, sessionToken, otp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.AuthnResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, sessionToken, otp)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OTPAuthnInterfaceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type OTPAuthnInterfaceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
//   - otp string
func (_e *OTPAuthnInterfaceMock_Expecter) Authenticate(ctx interface{}, sessionToken interface{}, otp interface{}) *OTPAuthnInterfaceMock_Authenticate_Call {
	return &OTPAuthnInterfaceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, sessionToken, otp)}
}

func (_c *OTPAuthnInterfaceMock_Authenticate_Call) Run(run func(ctx context.Context, sessionToken string, otp string)) *OTPAuthnInterfaceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OTPAuthnInterfaceMock_Authenticate_Call) Return(authnResult *common.AuthnResult, serviceError *serviceerror.ServiceError) *OTPAuthnInterfaceMock_Authenticate_Call {
	_c.Call.Return(authnResult, serviceError)
	return _c
}

func (_c *OTPAuthnInterfaceMock_Authenticate_Call) RunAndReturn(run func(ctx context.Context, sessionToken string, otp string) (*common.AuthnResult, *serviceerror.ServiceError)) *OTPAuthnInterfaceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// SendOTP provides a mock function for the type OTPAuthnInterfaceMock
func (_mock *OTPAuthnInterfaceMock) SendOTP(ctx context.Context, senderID string, channel common0.ChannelType, recipient string) (string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, senderID, channel, recipient)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, common0.ChannelType, string) (string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, senderID, channel, recipient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, common0.ChannelType, string) string); ok {
		r0 = returnFunc(ctx, senderID, channel, recipient)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, common0.ChannelType, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, senderID, channel, recipient)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OTPAuthnInterfaceMock_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type OTPAuthnInterfaceMock_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID string
//   - channel common0.ChannelType
//   - recipient string
func (_e *OTPAuthnInterfaceMock_Expecter) SendOTP(ctx interface{}, senderID interface{}, channel interface{}, recipient interface{}) *OTPAuthnInterfaceMock_SendOTP_Call {
	return &OTPAuthnInterfaceMock_SendOTP_Call{Call: _e.mock.On("SendOTP", ctx, senderID, channel, recipient)}
}

func (_c *OTPAuthnInterfaceMock_SendOTP_Call) Run(run func(ctx context.Context, senderID string, channel common0.ChannelType, recipient string)) *OTPAuthnInterfaceMock_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 common0.ChannelType
		if args[2] != nil {
			arg2 = args[2].(common0.ChannelType)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OTPAuthnInterfaceMock_SendOTP_Call) Return(s string, serviceError *serviceerror.ServiceError) *OTPAuthnInterfaceMock_SendOTP_Call {
	_c.Call.Return(s, serviceError)
	return _c
}

func (_c *OTPAuthnInterfaceMock_SendOTP_Call) RunAndReturn(run func(ctx context.Context, senderID string, channel common0.ChannelType, recipient string) (string, *serviceerror.ServiceError)) *OTPAuthnInterfaceMock_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function for the type OTPAuthnInterfaceMock
func (_mock *OTPAuthnInterfaceMock) VerifyOTP(ctx context.Context, sessionToken string, otp string) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, sessionToken, otp)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, sessionToken, otp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// OTPAuthnInterfaceMock_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type OTPAuthnInterfaceMock_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
//   - otp string
func (_e *OTPAuthnInterfaceMock_Expecter) VerifyOTP(ctx interface{}, sessionToken interface{}, otp interface{}) *OTPAuthnInterfaceMock_VerifyOTP_Call {
	return &OTPAuthnInterfaceMock_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, sessionToken, otp)}
}

func (_c *OTPAuthnInterfaceMock_VerifyOTP_Call) Run(run func(ctx context.Context, sessionToken string, otp string)) *OTPAuthnInterfaceMock_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OTPAuthnInterfaceMock_VerifyOTP_Call) Return(serviceError *serviceerror.ServiceError) *OTPAuthnInterfaceMock_VerifyOTP_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *OTPAuthnInterfaceMock_VerifyOTP_Call) RunAndReturn(run func(ctx context.Context, sessionToken string, otp string) *serviceerror.ServiceError) *OTPAuthnInterfaceMock_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}
