// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usermock

import (
	"context"

	"github.com/asgardeo/thunder/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// newUserStoreInterfaceMock creates a new instance of userStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newUserStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *userStoreInterfaceMock {
	mock := &userStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// userStoreInterfaceMock is an autogenerated mock type for the userStoreInterface type
type userStoreInterfaceMock struct {
	mock.Mock
}

type userStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *userStoreInterfaceMock) EXPECT() *userStoreInterfaceMock_Expecter {
	return &userStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) CreateUser(ctx context.Context, user1 user.User, credentials user.Credentials) error {
	ret := _mock.Called(ctx, user1, credentials)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User, user.Credentials) error); ok {
		r0 = returnFunc(ctx, user1, credentials)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userStoreInterfaceMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type userStoreInterfaceMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 user.User
//   - credentials user.Credentials
func (_e *userStoreInterfaceMock_Expecter) CreateUser(ctx interface{}, user1 interface{}, credentials interface{}) *userStoreInterfaceMock_CreateUser_Call {
	return &userStoreInterfaceMock_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user1, credentials)}
}

func (_c *userStoreInterfaceMock_CreateUser_Call) Run(run func(ctx context.Context, user1 user.User, credentials user.Credentials)) *userStoreInterfaceMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		var arg2 user.Credentials
		if args[2] != nil {
			arg2 = args[2].(user.Credentials)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_CreateUser_Call) Return(err error) *userStoreInterfaceMock_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userStoreInterfaceMock_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user1 user.User, credentials user.Credentials) error) *userStoreInterfaceMock_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) DeleteUser(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userStoreInterfaceMock_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type userStoreInterfaceMock_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *userStoreInterfaceMock_Expecter) DeleteUser(ctx interface{}, id interface{}) *userStoreInterfaceMock_DeleteUser_Call {
	return &userStoreInterfaceMock_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *userStoreInterfaceMock_DeleteUser_Call) Run(run func(ctx context.Context, id string)) *userStoreInterfaceMock_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_DeleteUser_Call) Return(err error) *userStoreInterfaceMock_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userStoreInterfaceMock_DeleteUser_Call) RunAndReturn(run func(id string) error) *userStoreInterfaceMock_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) GetCredentials(ctx context.Context, id string) (user.User, user.Credentials, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 user.User
	var r1 user.Credentials
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (user.User, user.Credentials, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) user.Credentials); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(user.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// userStoreInterfaceMock_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type userStoreInterfaceMock_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *userStoreInterfaceMock_Expecter) GetCredentials(ctx interface{}, id interface{}) *userStoreInterfaceMock_GetCredentials_Call {
	return &userStoreInterfaceMock_GetCredentials_Call{Call: _e.mock.On("GetCredentials", ctx, id)}
}

func (_c *userStoreInterfaceMock_GetCredentials_Call) Run(run func(ctx context.Context, id string)) *userStoreInterfaceMock_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_GetCredentials_Call) Return(user1 user.User, credentials user.Credentials, err error) *userStoreInterfaceMock_GetCredentials_Call {
	_c.Call.Return(user1, credentials, err)
	return _c
}

func (_c *userStoreInterfaceMock_GetCredentials_Call) RunAndReturn(run func(ctx context.Context, id string) (user.User, user.Credentials, error)) *userStoreInterfaceMock_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupCountForUser provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) GetGroupCountForUser(ctx context.Context, userID string) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupCountForUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userStoreInterfaceMock_GetGroupCountForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupCountForUser'
type userStoreInterfaceMock_GetGroupCountForUser_Call struct {
	*mock.Call
}

// GetGroupCountForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *userStoreInterfaceMock_Expecter) GetGroupCountForUser(ctx interface{}, userID interface{}) *userStoreInterfaceMock_GetGroupCountForUser_Call {
	return &userStoreInterfaceMock_GetGroupCountForUser_Call{Call: _e.mock.On("GetGroupCountForUser", ctx, userID)}
}

func (_c *userStoreInterfaceMock_GetGroupCountForUser_Call) Run(run func(ctx context.Context, userID string)) *userStoreInterfaceMock_GetGroupCountForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_GetGroupCountForUser_Call) Return(n int, err error) *userStoreInterfaceMock_GetGroupCountForUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *userStoreInterfaceMock_GetGroupCountForUser_Call) RunAndReturn(run func(ctx context.Context, userID string) (int, error)) *userStoreInterfaceMock_GetGroupCountForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) GetUser(ctx context.Context, id string) (user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (user.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) user.User); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userStoreInterfaceMock_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type userStoreInterfaceMock_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *userStoreInterfaceMock_Expecter) GetUser(ctx interface{}, id interface{}) *userStoreInterfaceMock_GetUser_Call {
	return &userStoreInterfaceMock_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *userStoreInterfaceMock_GetUser_Call) Run(run func(ctx context.Context, id string)) *userStoreInterfaceMock_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_GetUser_Call) Return(user1 user.User, err error) *userStoreInterfaceMock_GetUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *userStoreInterfaceMock_GetUser_Call) RunAndReturn(run func(ctx context.Context, id string) (user.User, error)) *userStoreInterfaceMock_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGroups provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) GetUserGroups(ctx context.Context, userID string, limit int, offset int) ([]user.UserGroup, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroups")
	}

	var r0 []user.UserGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]user.UserGroup, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []user.UserGroup); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UserGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userStoreInterfaceMock_GetUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGroups'
type userStoreInterfaceMock_GetUserGroups_Call struct {
	*mock.Call
}

// GetUserGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *userStoreInterfaceMock_Expecter) GetUserGroups(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *userStoreInterfaceMock_GetUserGroups_Call {
	return &userStoreInterfaceMock_GetUserGroups_Call{Call: _e.mock.On("GetUserGroups", ctx, userID, limit, offset)}
}

func (_c *userStoreInterfaceMock_GetUserGroups_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *userStoreInterfaceMock_GetUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_GetUserGroups_Call) Return(userGroups []user.UserGroup, err error) *userStoreInterfaceMock_GetUserGroups_Call {
	_c.Call.Return(userGroups, err)
	return _c
}

func (_c *userStoreInterfaceMock_GetUserGroups_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int, offset int) ([]user.UserGroup, error)) *userStoreInterfaceMock_GetUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserList provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) GetUserList(ctx context.Context, limit int, offset int, filters map[string]interface{}) ([]user.User, error) {
	ret := _mock.Called(ctx, limit, offset, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetUserList")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, map[string]interface{}) ([]user.User, error)); ok {
		return returnFunc(ctx, limit, offset, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, map[string]interface{}) []user.User); ok {
		r0 = returnFunc(ctx, limit, offset, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, limit, offset, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userStoreInterfaceMock_GetUserList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserList'
type userStoreInterfaceMock_GetUserList_Call struct {
	*mock.Call
}

// GetUserList is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - filters map[string]interface{}
func (_e *userStoreInterfaceMock_Expecter) GetUserList(ctx interface{}, limit interface{}, offset interface{}, filters interface{}) *userStoreInterfaceMock_GetUserList_Call {
	return &userStoreInterfaceMock_GetUserList_Call{Call: _e.mock.On("GetUserList", ctx, limit, offset, filters)}
}

func (_c *userStoreInterfaceMock_GetUserList_Call) Run(run func(ctx context.Context, limit int, offset int, filters map[string]interface{})) *userStoreInterfaceMock_GetUserList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_GetUserList_Call) Return(users []user.User, err error) *userStoreInterfaceMock_GetUserList_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *userStoreInterfaceMock_GetUserList_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int, filters map[string]interface{}) ([]user.User, error)) *userStoreInterfaceMock_GetUserList_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserListCount provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) GetUserListCount(ctx context.Context, filters map[string]interface{}) (int, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetUserListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (int, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) int); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userStoreInterfaceMock_GetUserListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserListCount'
type userStoreInterfaceMock_GetUserListCount_Call struct {
	*mock.Call
}

// GetUserListCount is a helper method to define mock.On call
//   - ctx context.Context
//   - filters map[string]interface{}
func (_e *userStoreInterfaceMock_Expecter) GetUserListCount(ctx interface{}, filters interface{}) *userStoreInterfaceMock_GetUserListCount_Call {
	return &userStoreInterfaceMock_GetUserListCount_Call{Call: _e.mock.On("GetUserListCount", ctx, filters)}
}

func (_c *userStoreInterfaceMock_GetUserListCount_Call) Run(run func(ctx context.Context, filters map[string]interface{})) *userStoreInterfaceMock_GetUserListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_GetUserListCount_Call) Return(n int, err error) *userStoreInterfaceMock_GetUserListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *userStoreInterfaceMock_GetUserListCount_Call) RunAndReturn(run func(ctx context.Context, filters map[string]interface{}) (int, error)) *userStoreInterfaceMock_GetUserListCount_Call {
	_c.Call.Return(run)
	return _c
}

// IdentifyUser provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) IdentifyUser(ctx context.Context, filters map[string]interface{}) (*string, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for IdentifyUser")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (*string, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) *string); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userStoreInterfaceMock_IdentifyUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentifyUser'
type userStoreInterfaceMock_IdentifyUser_Call struct {
	*mock.Call
}

// IdentifyUser is a helper method to define mock.On call
//   - ctx context.Context
//   - filters map[string]interface{}
func (_e *userStoreInterfaceMock_Expecter) IdentifyUser(ctx interface{}, filters interface{}) *userStoreInterfaceMock_IdentifyUser_Call {
	return &userStoreInterfaceMock_IdentifyUser_Call{Call: _e.mock.On("IdentifyUser", ctx, filters)}
}

func (_c *userStoreInterfaceMock_IdentifyUser_Call) Run(run func(ctx context.Context, filters map[string]interface{})) *userStoreInterfaceMock_IdentifyUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_IdentifyUser_Call) Return(s *string, err error) *userStoreInterfaceMock_IdentifyUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *userStoreInterfaceMock_IdentifyUser_Call) RunAndReturn(run func(ctx context.Context, filters map[string]interface{}) (*string, error)) *userStoreInterfaceMock_IdentifyUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) UpdateUser(ctx context.Context, user1 *user.User) error {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userStoreInterfaceMock_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type userStoreInterfaceMock_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
func (_e *userStoreInterfaceMock_Expecter) UpdateUser(ctx interface{}, user1 interface{}) *userStoreInterfaceMock_UpdateUser_Call {
	return &userStoreInterfaceMock_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user1)}
}

func (_c *userStoreInterfaceMock_UpdateUser_Call) Run(run func(ctx context.Context, user1 *user.User)) *userStoreInterfaceMock_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_UpdateUser_Call) Return(err error) *userStoreInterfaceMock_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userStoreInterfaceMock_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User) error) *userStoreInterfaceMock_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserCredentials provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) UpdateUserCredentials(ctx context.Context, userID string, credentials user.Credentials) error {
	ret := _mock.Called(ctx, userID, credentials)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserCredentials")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, user.Credentials) error); ok {
		r0 = returnFunc(ctx, userID, credentials)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userStoreInterfaceMock_UpdateUserCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserCredentials'
type userStoreInterfaceMock_UpdateUserCredentials_Call struct {
	*mock.Call
}

// UpdateUserCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - credentials user.Credentials
func (_e *userStoreInterfaceMock_Expecter) UpdateUserCredentials(ctx interface{}, userID interface{}, credentials interface{}) *userStoreInterfaceMock_UpdateUserCredentials_Call {
	return &userStoreInterfaceMock_UpdateUserCredentials_Call{Call: _e.mock.On("UpdateUserCredentials", ctx, userID, credentials)}
}

func (_c *userStoreInterfaceMock_UpdateUserCredentials_Call) Run(run func(ctx context.Context, userID string, credentials user.Credentials)) *userStoreInterfaceMock_UpdateUserCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 user.Credentials
		if args[2] != nil {
			arg2 = args[2].(user.Credentials)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_UpdateUserCredentials_Call) Return(err error) *userStoreInterfaceMock_UpdateUserCredentials_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userStoreInterfaceMock_UpdateUserCredentials_Call) RunAndReturn(run func(ctx context.Context, userID string, credentials user.Credentials) error) *userStoreInterfaceMock_UpdateUserCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUserIDs provides a mock function for the type userStoreInterfaceMock
func (_mock *userStoreInterfaceMock) ValidateUserIDs(ctx context.Context, userIDs []string) ([]string, error) {
	ret := _mock.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return returnFunc(ctx, userIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = returnFunc(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userStoreInterfaceMock_ValidateUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserIDs'
type userStoreInterfaceMock_ValidateUserIDs_Call struct {
	*mock.Call
}

// ValidateUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []string
func (_e *userStoreInterfaceMock_Expecter) ValidateUserIDs(ctx interface{}, userIDs interface{}) *userStoreInterfaceMock_ValidateUserIDs_Call {
	return &userStoreInterfaceMock_ValidateUserIDs_Call{Call: _e.mock.On("ValidateUserIDs", ctx, userIDs)}
}

func (_c *userStoreInterfaceMock_ValidateUserIDs_Call) Run(run func(ctx context.Context, userIDs []string)) *userStoreInterfaceMock_ValidateUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userStoreInterfaceMock_ValidateUserIDs_Call) Return(strings []string, err error) *userStoreInterfaceMock_ValidateUserIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *userStoreInterfaceMock_ValidateUserIDs_Call) RunAndReturn(run func(ctx context.Context, userIDs []string) ([]string, error)) *userStoreInterfaceMock_ValidateUserIDs_Call {
	_c.Call.Return(run)
	return _c
}
