-- Table to store Organization Units
CREATE TABLE ORGANIZATION_UNIT (
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    OU_ID           VARCHAR(36) PRIMARY KEY,
    PARENT_ID       VARCHAR(36),
    HANDLE          VARCHAR(100)        NOT NULL,
    NAME            VARCHAR(100)        NOT NULL,
    DESCRIPTION     VARCHAR(255),
    THEME_ID        VARCHAR(36),
    LAYOUT_ID       VARCHAR(36),
    METADATA         JSONB,
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW()
);

-- Composite index for handle-based OU lookups
CREATE INDEX idx_ou_handle_parent ON ORGANIZATION_UNIT (DEPLOYMENT_ID, HANDLE, PARENT_ID);

-- Table to store Users
CREATE TABLE "USER" (
    DEPLOYMENT_ID   VARCHAR(255) NOT NULL,
    ID          VARCHAR(36)        PRIMARY KEY,
    OU_ID       VARCHAR(36)        NOT NULL,
    TYPE        VARCHAR(50)        NOT NULL,
    ATTRIBUTES  JSONB,
    CREDENTIALS JSONB,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW()
);

-- Composite index for OU-based user listing
CREATE INDEX idx_user_ou_deployment ON "USER" (DEPLOYMENT_ID, OU_ID);

-- Table to store Groups
CREATE TABLE "GROUP" (
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    ID              VARCHAR(36)        PRIMARY KEY,
    OU_ID           VARCHAR(36)        NOT NULL,
    NAME            VARCHAR(50)        NOT NULL,
    DESCRIPTION     VARCHAR(255),
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW()
);

-- Composite index for name conflict checks within an OU
CREATE INDEX idx_group_name_ou_deployment ON "GROUP" (DEPLOYMENT_ID, OU_ID, NAME);

-- Table to store Group member assignments
CREATE TABLE GROUP_MEMBER_REFERENCE (
    DEPLOYMENT_ID   VARCHAR(255) NOT NULL,
    GROUP_ID    VARCHAR(36) NOT NULL,
    MEMBER_TYPE VARCHAR(7)  NOT NULL,
    MEMBER_ID   VARCHAR(36) NOT NULL,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (GROUP_ID, MEMBER_TYPE, MEMBER_ID, DEPLOYMENT_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES "GROUP" (ID) ON DELETE CASCADE
);

-- Table to store indexed user attributes for fast lookups
CREATE TABLE USER_INDEXED_ATTRIBUTES (
    DEPLOYMENT_ID   VARCHAR(255) NOT NULL,
    USER_ID         VARCHAR(36) NOT NULL,
    ATTRIBUTE_NAME  VARCHAR(255) NOT NULL,
    ATTRIBUTE_VALUE TEXT NOT NULL,
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (USER_ID, DEPLOYMENT_ID, ATTRIBUTE_NAME),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID) ON DELETE CASCADE
);

-- Index for fast attribute lookups (primary use case for authentication)
CREATE INDEX idx_user_indexed_attributes_lookup ON USER_INDEXED_ATTRIBUTES (ATTRIBUTE_NAME, ATTRIBUTE_VALUE);
