name: Setup Go
description: Sets up Go environment
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version-file: backend/go.mod
