// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actorprovider

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/entityprovider"
	"github.com/thunder-id/thunderid/internal/inboundclient/model"
	"github.com/thunder-id/thunderid/internal/system/error/serviceerror"
)

// NewActorProviderInterfaceMock creates a new instance of ActorProviderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActorProviderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActorProviderInterfaceMock {
	mock := &ActorProviderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ActorProviderInterfaceMock is an autogenerated mock type for the ActorProviderInterface type
type ActorProviderInterfaceMock struct {
	mock.Mock
}

type ActorProviderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ActorProviderInterfaceMock) EXPECT() *ActorProviderInterfaceMock_Expecter {
	return &ActorProviderInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetActor provides a mock function for the type ActorProviderInterfaceMock
func (_mock *ActorProviderInterfaceMock) GetActor(actorID string) (*entityprovider.Entity, *entityprovider.EntityProviderError) {
	ret := _mock.Called(actorID)

	if len(ret) == 0 {
		panic("no return value specified for GetActor")
	}

	var r0 *entityprovider.Entity
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string) (*entityprovider.Entity, *entityprovider.EntityProviderError)); ok {
		return returnFunc(actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entityprovider.Entity); ok {
		r0 = returnFunc(actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(actorID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// ActorProviderInterfaceMock_GetActor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActor'
type ActorProviderInterfaceMock_GetActor_Call struct {
	*mock.Call
}

// GetActor is a helper method to define mock.On call
//   - actorID string
func (_e *ActorProviderInterfaceMock_Expecter) GetActor(actorID interface{}) *ActorProviderInterfaceMock_GetActor_Call {
	return &ActorProviderInterfaceMock_GetActor_Call{Call: _e.mock.On("GetActor", actorID)}
}

func (_c *ActorProviderInterfaceMock_GetActor_Call) Run(run func(actorID string)) *ActorProviderInterfaceMock_GetActor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ActorProviderInterfaceMock_GetActor_Call) Return(entity *entityprovider.Entity, entityProviderError *entityprovider.EntityProviderError) *ActorProviderInterfaceMock_GetActor_Call {
	_c.Call.Return(entity, entityProviderError)
	return _c
}

func (_c *ActorProviderInterfaceMock_GetActor_Call) RunAndReturn(run func(actorID string) (*entityprovider.Entity, *entityprovider.EntityProviderError)) *ActorProviderInterfaceMock_GetActor_Call {
	_c.Call.Return(run)
	return _c
}

// GetActorGroups provides a mock function for the type ActorProviderInterfaceMock
func (_mock *ActorProviderInterfaceMock) GetActorGroups(actorID string) ([]entityprovider.EntityGroup, *entityprovider.EntityProviderError) {
	ret := _mock.Called(actorID)

	if len(ret) == 0 {
		panic("no return value specified for GetActorGroups")
	}

	var r0 []entityprovider.EntityGroup
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string) ([]entityprovider.EntityGroup, *entityprovider.EntityProviderError)); ok {
		return returnFunc(actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []entityprovider.EntityGroup); ok {
		r0 = returnFunc(actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entityprovider.EntityGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(actorID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// ActorProviderInterfaceMock_GetActorGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActorGroups'
type ActorProviderInterfaceMock_GetActorGroups_Call struct {
	*mock.Call
}

// GetActorGroups is a helper method to define mock.On call
//   - actorID string
func (_e *ActorProviderInterfaceMock_Expecter) GetActorGroups(actorID interface{}) *ActorProviderInterfaceMock_GetActorGroups_Call {
	return &ActorProviderInterfaceMock_GetActorGroups_Call{Call: _e.mock.On("GetActorGroups", actorID)}
}

func (_c *ActorProviderInterfaceMock_GetActorGroups_Call) Run(run func(actorID string)) *ActorProviderInterfaceMock_GetActorGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ActorProviderInterfaceMock_GetActorGroups_Call) Return(entityGroups []entityprovider.EntityGroup, entityProviderError *entityprovider.EntityProviderError) *ActorProviderInterfaceMock_GetActorGroups_Call {
	_c.Call.Return(entityGroups, entityProviderError)
	return _c
}

func (_c *ActorProviderInterfaceMock_GetActorGroups_Call) RunAndReturn(run func(actorID string) ([]entityprovider.EntityGroup, *entityprovider.EntityProviderError)) *ActorProviderInterfaceMock_GetActorGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetInboundClientByID provides a mock function for the type ActorProviderInterfaceMock
func (_mock *ActorProviderInterfaceMock) GetInboundClientByID(ctx context.Context, id string) (*model.InboundClient, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInboundClientByID")
	}

	var r0 *model.InboundClient
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.InboundClient, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.InboundClient); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InboundClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ActorProviderInterfaceMock_GetInboundClientByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInboundClientByID'
type ActorProviderInterfaceMock_GetInboundClientByID_Call struct {
	*mock.Call
}

// GetInboundClientByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ActorProviderInterfaceMock_Expecter) GetInboundClientByID(ctx interface{}, id interface{}) *ActorProviderInterfaceMock_GetInboundClientByID_Call {
	return &ActorProviderInterfaceMock_GetInboundClientByID_Call{Call: _e.mock.On("GetInboundClientByID", ctx, id)}
}

func (_c *ActorProviderInterfaceMock_GetInboundClientByID_Call) Run(run func(ctx context.Context, id string)) *ActorProviderInterfaceMock_GetInboundClientByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ActorProviderInterfaceMock_GetInboundClientByID_Call) Return(inboundClient *model.InboundClient, serviceError *serviceerror.ServiceError) *ActorProviderInterfaceMock_GetInboundClientByID_Call {
	_c.Call.Return(inboundClient, serviceError)
	return _c
}

func (_c *ActorProviderInterfaceMock_GetInboundClientByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.InboundClient, *serviceerror.ServiceError)) *ActorProviderInterfaceMock_GetInboundClientByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthClientByID provides a mock function for the type ActorProviderInterfaceMock
func (_mock *ActorProviderInterfaceMock) GetOAuthClientByID(ctx context.Context, id string) (*model.OAuthClient, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthClientByID")
	}

	var r0 *model.OAuthClient
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.OAuthClient, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.OAuthClient); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OAuthClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ActorProviderInterfaceMock_GetOAuthClientByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthClientByID'
type ActorProviderInterfaceMock_GetOAuthClientByID_Call struct {
	*mock.Call
}

// GetOAuthClientByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ActorProviderInterfaceMock_Expecter) GetOAuthClientByID(ctx interface{}, id interface{}) *ActorProviderInterfaceMock_GetOAuthClientByID_Call {
	return &ActorProviderInterfaceMock_GetOAuthClientByID_Call{Call: _e.mock.On("GetOAuthClientByID", ctx, id)}
}

func (_c *ActorProviderInterfaceMock_GetOAuthClientByID_Call) Run(run func(ctx context.Context, id string)) *ActorProviderInterfaceMock_GetOAuthClientByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ActorProviderInterfaceMock_GetOAuthClientByID_Call) Return(oAuthClient *model.OAuthClient, serviceError *serviceerror.ServiceError) *ActorProviderInterfaceMock_GetOAuthClientByID_Call {
	_c.Call.Return(oAuthClient, serviceError)
	return _c
}

func (_c *ActorProviderInterfaceMock_GetOAuthClientByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.OAuthClient, *serviceerror.ServiceError)) *ActorProviderInterfaceMock_GetOAuthClientByID_Call {
	_c.Call.Return(run)
	return _c
}
