// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providermock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/system/database/provider"
	"github.com/thunder-id/thunderid/internal/system/transaction"
)

// NewDBProviderInterfaceMock creates a new instance of DBProviderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBProviderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBProviderInterfaceMock {
	mock := &DBProviderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DBProviderInterfaceMock is an autogenerated mock type for the DBProviderInterface type
type DBProviderInterfaceMock struct {
	mock.Mock
}

type DBProviderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DBProviderInterfaceMock) EXPECT() *DBProviderInterfaceMock_Expecter {
	return &DBProviderInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetConfigDBClient provides a mock function for the type DBProviderInterfaceMock
func (_mock *DBProviderInterfaceMock) GetConfigDBClient() (provider.DBClientInterface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigDBClient")
	}

	var r0 provider.DBClientInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (provider.DBClientInterface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() provider.DBClientInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provider.DBClientInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBProviderInterfaceMock_GetConfigDBClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigDBClient'
type DBProviderInterfaceMock_GetConfigDBClient_Call struct {
	*mock.Call
}

// GetConfigDBClient is a helper method to define mock.On call
func (_e *DBProviderInterfaceMock_Expecter) GetConfigDBClient() *DBProviderInterfaceMock_GetConfigDBClient_Call {
	return &DBProviderInterfaceMock_GetConfigDBClient_Call{Call: _e.mock.On("GetConfigDBClient")}
}

func (_c *DBProviderInterfaceMock_GetConfigDBClient_Call) Run(run func()) *DBProviderInterfaceMock_GetConfigDBClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProviderInterfaceMock_GetConfigDBClient_Call) Return(dBClientInterface provider.DBClientInterface, err error) *DBProviderInterfaceMock_GetConfigDBClient_Call {
	_c.Call.Return(dBClientInterface, err)
	return _c
}

func (_c *DBProviderInterfaceMock_GetConfigDBClient_Call) RunAndReturn(run func() (provider.DBClientInterface, error)) *DBProviderInterfaceMock_GetConfigDBClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigDBTransactioner provides a mock function for the type DBProviderInterfaceMock
func (_mock *DBProviderInterfaceMock) GetConfigDBTransactioner() (transaction.Transactioner, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigDBTransactioner")
	}

	var r0 transaction.Transactioner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (transaction.Transactioner, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() transaction.Transactioner); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transaction.Transactioner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBProviderInterfaceMock_GetConfigDBTransactioner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigDBTransactioner'
type DBProviderInterfaceMock_GetConfigDBTransactioner_Call struct {
	*mock.Call
}

// GetConfigDBTransactioner is a helper method to define mock.On call
func (_e *DBProviderInterfaceMock_Expecter) GetConfigDBTransactioner() *DBProviderInterfaceMock_GetConfigDBTransactioner_Call {
	return &DBProviderInterfaceMock_GetConfigDBTransactioner_Call{Call: _e.mock.On("GetConfigDBTransactioner")}
}

func (_c *DBProviderInterfaceMock_GetConfigDBTransactioner_Call) Run(run func()) *DBProviderInterfaceMock_GetConfigDBTransactioner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProviderInterfaceMock_GetConfigDBTransactioner_Call) Return(transactioner transaction.Transactioner, err error) *DBProviderInterfaceMock_GetConfigDBTransactioner_Call {
	_c.Call.Return(transactioner, err)
	return _c
}

func (_c *DBProviderInterfaceMock_GetConfigDBTransactioner_Call) RunAndReturn(run func() (transaction.Transactioner, error)) *DBProviderInterfaceMock_GetConfigDBTransactioner_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityDBClient provides a mock function for the type DBProviderInterfaceMock
func (_mock *DBProviderInterfaceMock) GetEntityDBClient() (provider.DBClientInterface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEntityDBClient")
	}

	var r0 provider.DBClientInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (provider.DBClientInterface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() provider.DBClientInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provider.DBClientInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBProviderInterfaceMock_GetEntityDBClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityDBClient'
type DBProviderInterfaceMock_GetEntityDBClient_Call struct {
	*mock.Call
}

// GetEntityDBClient is a helper method to define mock.On call
func (_e *DBProviderInterfaceMock_Expecter) GetEntityDBClient() *DBProviderInterfaceMock_GetEntityDBClient_Call {
	return &DBProviderInterfaceMock_GetEntityDBClient_Call{Call: _e.mock.On("GetEntityDBClient")}
}

func (_c *DBProviderInterfaceMock_GetEntityDBClient_Call) Run(run func()) *DBProviderInterfaceMock_GetEntityDBClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProviderInterfaceMock_GetEntityDBClient_Call) Return(dBClientInterface provider.DBClientInterface, err error) *DBProviderInterfaceMock_GetEntityDBClient_Call {
	_c.Call.Return(dBClientInterface, err)
	return _c
}

func (_c *DBProviderInterfaceMock_GetEntityDBClient_Call) RunAndReturn(run func() (provider.DBClientInterface, error)) *DBProviderInterfaceMock_GetEntityDBClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityDBTransactioner provides a mock function for the type DBProviderInterfaceMock
func (_mock *DBProviderInterfaceMock) GetEntityDBTransactioner() (transaction.Transactioner, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEntityDBTransactioner")
	}

	var r0 transaction.Transactioner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (transaction.Transactioner, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() transaction.Transactioner); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transaction.Transactioner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBProviderInterfaceMock_GetEntityDBTransactioner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityDBTransactioner'
type DBProviderInterfaceMock_GetEntityDBTransactioner_Call struct {
	*mock.Call
}

// GetEntityDBTransactioner is a helper method to define mock.On call
func (_e *DBProviderInterfaceMock_Expecter) GetEntityDBTransactioner() *DBProviderInterfaceMock_GetEntityDBTransactioner_Call {
	return &DBProviderInterfaceMock_GetEntityDBTransactioner_Call{Call: _e.mock.On("GetEntityDBTransactioner")}
}

func (_c *DBProviderInterfaceMock_GetEntityDBTransactioner_Call) Run(run func()) *DBProviderInterfaceMock_GetEntityDBTransactioner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProviderInterfaceMock_GetEntityDBTransactioner_Call) Return(transactioner transaction.Transactioner, err error) *DBProviderInterfaceMock_GetEntityDBTransactioner_Call {
	_c.Call.Return(transactioner, err)
	return _c
}

func (_c *DBProviderInterfaceMock_GetEntityDBTransactioner_Call) RunAndReturn(run func() (transaction.Transactioner, error)) *DBProviderInterfaceMock_GetEntityDBTransactioner_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperationDBClient provides a mock function for the type DBProviderInterfaceMock
func (_mock *DBProviderInterfaceMock) GetOperationDBClient() (provider.DBClientInterface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOperationDBClient")
	}

	var r0 provider.DBClientInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (provider.DBClientInterface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() provider.DBClientInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provider.DBClientInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBProviderInterfaceMock_GetOperationDBClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationDBClient'
type DBProviderInterfaceMock_GetOperationDBClient_Call struct {
	*mock.Call
}

// GetOperationDBClient is a helper method to define mock.On call
func (_e *DBProviderInterfaceMock_Expecter) GetOperationDBClient() *DBProviderInterfaceMock_GetOperationDBClient_Call {
	return &DBProviderInterfaceMock_GetOperationDBClient_Call{Call: _e.mock.On("GetOperationDBClient")}
}

func (_c *DBProviderInterfaceMock_GetOperationDBClient_Call) Run(run func()) *DBProviderInterfaceMock_GetOperationDBClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProviderInterfaceMock_GetOperationDBClient_Call) Return(dBClientInterface provider.DBClientInterface, err error) *DBProviderInterfaceMock_GetOperationDBClient_Call {
	_c.Call.Return(dBClientInterface, err)
	return _c
}

func (_c *DBProviderInterfaceMock_GetOperationDBClient_Call) RunAndReturn(run func() (provider.DBClientInterface, error)) *DBProviderInterfaceMock_GetOperationDBClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperationDBTransactioner provides a mock function for the type DBProviderInterfaceMock
func (_mock *DBProviderInterfaceMock) GetOperationDBTransactioner() (transaction.Transactioner, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOperationDBTransactioner")
	}

	var r0 transaction.Transactioner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (transaction.Transactioner, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() transaction.Transactioner); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transaction.Transactioner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBProviderInterfaceMock_GetOperationDBTransactioner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationDBTransactioner'
type DBProviderInterfaceMock_GetOperationDBTransactioner_Call struct {
	*mock.Call
}

// GetOperationDBTransactioner is a helper method to define mock.On call
func (_e *DBProviderInterfaceMock_Expecter) GetOperationDBTransactioner() *DBProviderInterfaceMock_GetOperationDBTransactioner_Call {
	return &DBProviderInterfaceMock_GetOperationDBTransactioner_Call{Call: _e.mock.On("GetOperationDBTransactioner")}
}

func (_c *DBProviderInterfaceMock_GetOperationDBTransactioner_Call) Run(run func()) *DBProviderInterfaceMock_GetOperationDBTransactioner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProviderInterfaceMock_GetOperationDBTransactioner_Call) Return(transactioner transaction.Transactioner, err error) *DBProviderInterfaceMock_GetOperationDBTransactioner_Call {
	_c.Call.Return(transactioner, err)
	return _c
}

func (_c *DBProviderInterfaceMock_GetOperationDBTransactioner_Call) RunAndReturn(run func() (transaction.Transactioner, error)) *DBProviderInterfaceMock_GetOperationDBTransactioner_Call {
	_c.Call.Return(run)
	return _c
}

// GetRuntimeDBClient provides a mock function for the type DBProviderInterfaceMock
func (_mock *DBProviderInterfaceMock) GetRuntimeDBClient() (provider.DBClientInterface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRuntimeDBClient")
	}

	var r0 provider.DBClientInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (provider.DBClientInterface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() provider.DBClientInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provider.DBClientInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBProviderInterfaceMock_GetRuntimeDBClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRuntimeDBClient'
type DBProviderInterfaceMock_GetRuntimeDBClient_Call struct {
	*mock.Call
}

// GetRuntimeDBClient is a helper method to define mock.On call
func (_e *DBProviderInterfaceMock_Expecter) GetRuntimeDBClient() *DBProviderInterfaceMock_GetRuntimeDBClient_Call {
	return &DBProviderInterfaceMock_GetRuntimeDBClient_Call{Call: _e.mock.On("GetRuntimeDBClient")}
}

func (_c *DBProviderInterfaceMock_GetRuntimeDBClient_Call) Run(run func()) *DBProviderInterfaceMock_GetRuntimeDBClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProviderInterfaceMock_GetRuntimeDBClient_Call) Return(dBClientInterface provider.DBClientInterface, err error) *DBProviderInterfaceMock_GetRuntimeDBClient_Call {
	_c.Call.Return(dBClientInterface, err)
	return _c
}

func (_c *DBProviderInterfaceMock_GetRuntimeDBClient_Call) RunAndReturn(run func() (provider.DBClientInterface, error)) *DBProviderInterfaceMock_GetRuntimeDBClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetRuntimeDBTransactioner provides a mock function for the type DBProviderInterfaceMock
func (_mock *DBProviderInterfaceMock) GetRuntimeDBTransactioner() (transaction.Transactioner, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRuntimeDBTransactioner")
	}

	var r0 transaction.Transactioner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (transaction.Transactioner, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() transaction.Transactioner); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transaction.Transactioner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRuntimeDBTransactioner'
type DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call struct {
	*mock.Call
}

// GetRuntimeDBTransactioner is a helper method to define mock.On call
func (_e *DBProviderInterfaceMock_Expecter) GetRuntimeDBTransactioner() *DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call {
	return &DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call{Call: _e.mock.On("GetRuntimeDBTransactioner")}
}

func (_c *DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call) Run(run func()) *DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call) Return(transactioner transaction.Transactioner, err error) *DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call {
	_c.Call.Return(transactioner, err)
	return _c
}

func (_c *DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call) RunAndReturn(run func() (transaction.Transactioner, error)) *DBProviderInterfaceMock_GetRuntimeDBTransactioner_Call {
	_c.Call.Return(run)
	return _c
}
