// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userschemamock

import (
	"context"

	"github.com/asgardeo/thunder/internal/userschema"
	mock "github.com/stretchr/testify/mock"
)

// newUserSchemaStoreInterfaceMock creates a new instance of userSchemaStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newUserSchemaStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *userSchemaStoreInterfaceMock {
	mock := &userSchemaStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// userSchemaStoreInterfaceMock is an autogenerated mock type for the userSchemaStoreInterface type
type userSchemaStoreInterfaceMock struct {
	mock.Mock
}

type userSchemaStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *userSchemaStoreInterfaceMock) EXPECT() *userSchemaStoreInterfaceMock_Expecter {
	return &userSchemaStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateUserSchema provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) CreateUserSchema(ctx context.Context, userSchema userschema.UserSchema) error {
	ret := _mock.Called(ctx, userSchema)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserSchema")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, userschema.UserSchema) error); ok {
		r0 = returnFunc(ctx, userSchema)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userSchemaStoreInterfaceMock_CreateUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserSchema'
type userSchemaStoreInterfaceMock_CreateUserSchema_Call struct {
	*mock.Call
}

// CreateUserSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - userSchema userschema.UserSchema
func (_e *userSchemaStoreInterfaceMock_Expecter) CreateUserSchema(ctx interface{}, userSchema interface{}) *userSchemaStoreInterfaceMock_CreateUserSchema_Call {
	return &userSchemaStoreInterfaceMock_CreateUserSchema_Call{Call: _e.mock.On("CreateUserSchema", ctx, userSchema)}
}

func (_c *userSchemaStoreInterfaceMock_CreateUserSchema_Call) Run(run func(ctx context.Context, userSchema userschema.UserSchema)) *userSchemaStoreInterfaceMock_CreateUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 userschema.UserSchema
		if args[1] != nil {
			arg1 = args[1].(userschema.UserSchema)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_CreateUserSchema_Call) Return(err error) *userSchemaStoreInterfaceMock_CreateUserSchema_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_CreateUserSchema_Call) RunAndReturn(run func(ctx context.Context, userSchema userschema.UserSchema) error) *userSchemaStoreInterfaceMock_CreateUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserSchemaByID provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) DeleteUserSchemaByID(ctx context.Context, schemaID string) error {
	ret := _mock.Called(ctx, schemaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserSchemaByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, schemaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserSchemaByID'
type userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call struct {
	*mock.Call
}

// DeleteUserSchemaByID is a helper method to define mock.On call
//   - ctx context.Context
//   - schemaID string
func (_e *userSchemaStoreInterfaceMock_Expecter) DeleteUserSchemaByID(ctx interface{}, schemaID interface{}) *userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call {
	return &userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call{Call: _e.mock.On("DeleteUserSchemaByID", ctx, schemaID)}
}

func (_c *userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call) Run(run func(ctx context.Context, schemaID string)) *userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call) Return(err error) *userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call) RunAndReturn(run func(ctx context.Context, schemaID string) error) *userSchemaStoreInterfaceMock_DeleteUserSchemaByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaByID provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) GetUserSchemaByID(ctx context.Context, schemaID string) (userschema.UserSchema, error) {
	ret := _mock.Called(ctx, schemaID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaByID")
	}

	var r0 userschema.UserSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (userschema.UserSchema, error)); ok {
		return returnFunc(ctx, schemaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) userschema.UserSchema); ok {
		r0 = returnFunc(ctx, schemaID)
	} else {
		r0 = ret.Get(0).(userschema.UserSchema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, schemaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userSchemaStoreInterfaceMock_GetUserSchemaByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaByID'
type userSchemaStoreInterfaceMock_GetUserSchemaByID_Call struct {
	*mock.Call
}

// GetUserSchemaByID is a helper method to define mock.On call
//   - ctx context.Context
//   - schemaID string
func (_e *userSchemaStoreInterfaceMock_Expecter) GetUserSchemaByID(ctx interface{}, schemaID interface{}) *userSchemaStoreInterfaceMock_GetUserSchemaByID_Call {
	return &userSchemaStoreInterfaceMock_GetUserSchemaByID_Call{Call: _e.mock.On("GetUserSchemaByID", ctx, schemaID)}
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaByID_Call) Run(run func(ctx context.Context, schemaID string)) *userSchemaStoreInterfaceMock_GetUserSchemaByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaByID_Call) Return(userSchema userschema.UserSchema, err error) *userSchemaStoreInterfaceMock_GetUserSchemaByID_Call {
	_c.Call.Return(userSchema, err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaByID_Call) RunAndReturn(run func(ctx context.Context, schemaID string) (userschema.UserSchema, error)) *userSchemaStoreInterfaceMock_GetUserSchemaByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaByName provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) GetUserSchemaByName(ctx context.Context, name string) (userschema.UserSchema, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaByName")
	}

	var r0 userschema.UserSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (userschema.UserSchema, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) userschema.UserSchema); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(userschema.UserSchema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userSchemaStoreInterfaceMock_GetUserSchemaByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaByName'
type userSchemaStoreInterfaceMock_GetUserSchemaByName_Call struct {
	*mock.Call
}

// GetUserSchemaByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *userSchemaStoreInterfaceMock_Expecter) GetUserSchemaByName(ctx interface{}, name interface{}) *userSchemaStoreInterfaceMock_GetUserSchemaByName_Call {
	return &userSchemaStoreInterfaceMock_GetUserSchemaByName_Call{Call: _e.mock.On("GetUserSchemaByName", ctx, name)}
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaByName_Call) Run(run func(ctx context.Context, name string)) *userSchemaStoreInterfaceMock_GetUserSchemaByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaByName_Call) Return(userSchema userschema.UserSchema, err error) *userSchemaStoreInterfaceMock_GetUserSchemaByName_Call {
	_c.Call.Return(userSchema, err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaByName_Call) RunAndReturn(run func(ctx context.Context, name string) (userschema.UserSchema, error)) *userSchemaStoreInterfaceMock_GetUserSchemaByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaList provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) GetUserSchemaList(ctx context.Context, limit int, offset int) ([]userschema.UserSchemaListItem, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaList")
	}

	var r0 []userschema.UserSchemaListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]userschema.UserSchemaListItem, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []userschema.UserSchemaListItem); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userschema.UserSchemaListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userSchemaStoreInterfaceMock_GetUserSchemaList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaList'
type userSchemaStoreInterfaceMock_GetUserSchemaList_Call struct {
	*mock.Call
}

// GetUserSchemaList is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *userSchemaStoreInterfaceMock_Expecter) GetUserSchemaList(ctx interface{}, limit interface{}, offset interface{}) *userSchemaStoreInterfaceMock_GetUserSchemaList_Call {
	return &userSchemaStoreInterfaceMock_GetUserSchemaList_Call{Call: _e.mock.On("GetUserSchemaList", ctx, limit, offset)}
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaList_Call) Run(run func(ctx context.Context, limit int, offset int)) *userSchemaStoreInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaList_Call) Return(userSchemaListItems []userschema.UserSchemaListItem, err error) *userSchemaStoreInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Return(userSchemaListItems, err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaList_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]userschema.UserSchemaListItem, error)) *userSchemaStoreInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaListByOUIDs provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) GetUserSchemaListByOUIDs(ctx context.Context, ouIDs []string, limit int, offset int) ([]userschema.UserSchemaListItem, error) {
	ret := _mock.Called(ctx, ouIDs, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaListByOUIDs")
	}

	var r0 []userschema.UserSchemaListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int, int) ([]userschema.UserSchemaListItem, error)); ok {
		return returnFunc(ctx, ouIDs, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int, int) []userschema.UserSchemaListItem); ok {
		r0 = returnFunc(ctx, ouIDs, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userschema.UserSchemaListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, int, int) error); ok {
		r1 = returnFunc(ctx, ouIDs, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaListByOUIDs'
type userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call struct {
	*mock.Call
}

// GetUserSchemaListByOUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ouIDs []string
//   - limit int
//   - offset int
func (_e *userSchemaStoreInterfaceMock_Expecter) GetUserSchemaListByOUIDs(ctx interface{}, ouIDs interface{}, limit interface{}, offset interface{}) *userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call {
	return &userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call{Call: _e.mock.On("GetUserSchemaListByOUIDs", ctx, ouIDs, limit, offset)}
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call) Run(run func(ctx context.Context, ouIDs []string, limit int, offset int)) *userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call) Return(userSchemaListItems []userschema.UserSchemaListItem, err error) *userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call {
	_c.Call.Return(userSchemaListItems, err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call) RunAndReturn(run func(ctx context.Context, ouIDs []string, limit int, offset int) ([]userschema.UserSchemaListItem, error)) *userSchemaStoreInterfaceMock_GetUserSchemaListByOUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaListCount provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) GetUserSchemaListCount(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaListCount'
type userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call struct {
	*mock.Call
}

// GetUserSchemaListCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *userSchemaStoreInterfaceMock_Expecter) GetUserSchemaListCount(ctx interface{}) *userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call {
	return &userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call{Call: _e.mock.On("GetUserSchemaListCount", ctx)}
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call) Run(run func(ctx context.Context)) *userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call) Return(n int, err error) *userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *userSchemaStoreInterfaceMock_GetUserSchemaListCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaListCountByOUIDs provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) GetUserSchemaListCountByOUIDs(ctx context.Context, ouIDs []string) (int, error) {
	ret := _mock.Called(ctx, ouIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaListCountByOUIDs")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (int, error)); ok {
		return returnFunc(ctx, ouIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) int); ok {
		r0 = returnFunc(ctx, ouIDs)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ouIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaListCountByOUIDs'
type userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call struct {
	*mock.Call
}

// GetUserSchemaListCountByOUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ouIDs []string
func (_e *userSchemaStoreInterfaceMock_Expecter) GetUserSchemaListCountByOUIDs(ctx interface{}, ouIDs interface{}) *userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call {
	return &userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call{Call: _e.mock.On("GetUserSchemaListCountByOUIDs", ctx, ouIDs)}
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call) Run(run func(ctx context.Context, ouIDs []string)) *userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call) Return(n int, err error) *userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call) RunAndReturn(run func(ctx context.Context, ouIDs []string) (int, error)) *userSchemaStoreInterfaceMock_GetUserSchemaListCountByOUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserSchemaDeclarative provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) IsUserSchemaDeclarative(schemaID string) bool {
	ret := _mock.Called(schemaID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserSchemaDeclarative")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(schemaID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserSchemaDeclarative'
type userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call struct {
	*mock.Call
}

// IsUserSchemaDeclarative is a helper method to define mock.On call
//   - schemaID string
func (_e *userSchemaStoreInterfaceMock_Expecter) IsUserSchemaDeclarative(schemaID interface{}) *userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call {
	return &userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call{Call: _e.mock.On("IsUserSchemaDeclarative", schemaID)}
}

func (_c *userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call) Run(run func(schemaID string)) *userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call) Return(b bool) *userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call) RunAndReturn(run func(schemaID string) bool) *userSchemaStoreInterfaceMock_IsUserSchemaDeclarative_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserSchemaByID provides a mock function for the type userSchemaStoreInterfaceMock
func (_mock *userSchemaStoreInterfaceMock) UpdateUserSchemaByID(ctx context.Context, schemaID string, userSchema userschema.UserSchema) error {
	ret := _mock.Called(ctx, schemaID, userSchema)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserSchemaByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, userschema.UserSchema) error); ok {
		r0 = returnFunc(ctx, schemaID, userSchema)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserSchemaByID'
type userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call struct {
	*mock.Call
}

// UpdateUserSchemaByID is a helper method to define mock.On call
//   - ctx context.Context
//   - schemaID string
//   - userSchema userschema.UserSchema
func (_e *userSchemaStoreInterfaceMock_Expecter) UpdateUserSchemaByID(ctx interface{}, schemaID interface{}, userSchema interface{}) *userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call {
	return &userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call{Call: _e.mock.On("UpdateUserSchemaByID", ctx, schemaID, userSchema)}
}

func (_c *userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call) Run(run func(ctx context.Context, schemaID string, userSchema userschema.UserSchema)) *userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 userschema.UserSchema
		if args[2] != nil {
			arg2 = args[2].(userschema.UserSchema)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call) Return(err error) *userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call) RunAndReturn(run func(ctx context.Context, schemaID string, userSchema userschema.UserSchema) error) *userSchemaStoreInterfaceMock_UpdateUserSchemaByID_Call {
	_c.Call.Return(run)
	return _c
}
