# Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

server:
  hostname: {{ .Values.configuration.consent.server.hostname | quote }}
  port: {{ .Values.configuration.consent.server.port }}
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 120s

database:
  consent:
    type: {{ .Values.configuration.consent.database.type | quote }}
    {{- if eq .Values.configuration.consent.database.type "sqlite" }}
    path: {{ .Values.configuration.consent.database.sqlitePath | quote }}
    options: {{ .Values.configuration.consent.database.sqliteOptions | quote }}
    {{- else }}
    hostname: {{ .Values.configuration.consent.database.host | quote }}
    port: {{ .Values.configuration.consent.database.port }}
    database: {{ .Values.configuration.consent.database.name | quote }}
    user: {{ .Values.configuration.consent.database.username | quote }}
    password: {{ "${DB_CONSENT_PASSWORD}" | quote }}
    sslmode: {{ .Values.configuration.consent.database.sslmode | quote }}
    max_open_conns: {{ .Values.configuration.consent.database.max_open_conns }}
    max_idle_conns: {{ .Values.configuration.consent.database.max_idle_conns }}
    conn_max_lifetime: {{ .Values.configuration.consent.database.conn_max_lifetime | quote }}
    {{- end }}

logging:
  level: info

consent:
  status_mappings:
    active_status: ACTIVE
    expired_status: EXPIRED
    revoked_status: REVOKED
    created_status: CREATED
    rejected_status: REJECTED
  auth_status_mappings:
    approved_state: APPROVED
    rejected_state: REJECTED
    created_state: CREATED
    system_expired_state: SYS_EXPIRED
    system_revoked_state: SYS_REVOKED
