// Code generated by i18n-extractor. DO NOT EDIT.
// Run 'make generate_i18n' to regenerate.

/*
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package core

// defaultMessages contains all i18n keys extracted from source code.
// This map is populated by the i18n extraction script at build time.
// Helper functions for accessing these messages are in helpers.go.
var defaultMessages = map[string]string{
	"error.consentenforcerservice.consent_create_failed": "Failed to create consent record",
	"error.consentenforcerservice.consent_create_failed_description": "Error while creating consent record in the consent service",
	"error.consentenforcerservice.consent_search_failed": "Failed to search consent records",
	"error.consentenforcerservice.consent_search_failed_description": "Error while searching for consent records from the consent service",
	"error.consentenforcerservice.consent_session_invalid": "Invalid consent session",
	"error.consentenforcerservice.consent_session_invalid_description": "The consent session token is invalid or has expired",
	"error.consentenforcerservice.consent_update_failed": "Failed to update consent record",
	"error.consentenforcerservice.consent_update_failed_description": "Error while updating consent record in the consent service",
	"error.consentenforcerservice.essential_consent_denied": "Essential consent denied",
	"error.consentenforcerservice.essential_consent_denied_description": "One or more essential consent attributes were denied",
	"error.consentenforcerservice.purpose_fetch_failed": "Failed to fetch consent purposes",
	"error.consentenforcerservice.purpose_fetch_failed_description": "Error while fetching consent purposes from the consent service",
	"error.consentservice.cannot_delete_element": "Cannot delete consent element",
	"error.consentservice.cannot_delete_purpose": "Cannot delete consent purpose",
	"error.consentservice.consent_not_found": "Consent not found",
	"error.consentservice.consent_not_found_description": "The consent record with the specified ID does not exist",
	"error.consentservice.delete_element_with_associated_purpose_description": "The consent element cannot be deleted because it is still associated with one or more consent purposes.",
	"error.consentservice.delete_purpose_with_associated_records_description": "The consent purpose cannot be deleted as it is associated with one or more consent records",
	"error.consentservice.element_already_exists": "Consent element already exists",
	"error.consentservice.element_already_exists_description": "A consent element with the same name already exists",
	"error.consentservice.element_not_found": "Consent element not found",
	"error.consentservice.element_not_found_description": "The consent element with the specified ID does not exist",
	"error.consentservice.forbidden": "Forbidden to access consent service",
	"error.consentservice.forbidden_description": "The consent service returned a forbidden response",
	"error.consentservice.invalid_consent_request": "Invalid consent request",
	"error.consentservice.invalid_consent_request_description": "The consent request was rejected by the consent service as invalid",
	"error.consentservice.invalid_element_request": "Invalid consent element request",
	"error.consentservice.invalid_element_request_description": "The consent element request was rejected by the consent service as invalid",
	"error.consentservice.invalid_purpose_request": "Invalid consent purpose request",
	"error.consentservice.invalid_purpose_request_description": "The consent purpose request was rejected by the consent service as invalid",
	"error.consentservice.invalid_request": "Invalid consent request",
	"error.consentservice.invalid_request_description": "The request sent to the consent service was invalid",
	"error.consentservice.invalid_request_format": "Invalid request format",
	"error.consentservice.invalid_request_format_description": "The request body is malformed or contains invalid data",
	"error.consentservice.invalid_revoke_request": "Invalid consent revoke request",
	"error.consentservice.invalid_revoke_request_description": "The consent revoke request was rejected by the consent service as invalid",
	"error.consentservice.invalid_search_filter": "Invalid consent search filter",
	"error.consentservice.invalid_search_filter_description": "The consent search filter was rejected by the consent service as invalid",
	"error.consentservice.invalid_update_request": "Invalid consent update request",
	"error.consentservice.invalid_update_request_description": "The consent update request was rejected by the consent service as invalid",
	"error.consentservice.invalid_validation_request": "Invalid consent validation request",
	"error.consentservice.invalid_validation_request_description": "The consent validation request was rejected by the consent service as invalid",
	"error.consentservice.purpose_already_exists": "Consent purpose already exists",
	"error.consentservice.purpose_already_exists_description": "A consent purpose with the same name already exists for this resource",
	"error.consentservice.purpose_not_found": "Consent purpose not found",
	"error.consentservice.purpose_not_found_description": "The consent purpose with the specified ID does not exist",
	"error.consentservice.unauthorized": "Unauthorized to access consent service",
	"error.consentservice.unauthorized_description": "The consent service returned an unauthorized response",
	"error.declarative_resource.create_operation_not_allowed": "Declarative resource create operation is not allowed",
	"error.declarative_resource.create_operation_not_allowed_description": "Creating declarative resources is not permitted",
	"error.declarative_resource.delete_operation_not_allowed": "Declarative resource delete operation is not allowed",
	"error.declarative_resource.delete_operation_not_allowed_description": "Deleting declarative resources is not permitted",
	"error.declarative_resource.update_operation_not_allowed": "Declarative resource update operation is not allowed",
	"error.declarative_resource.update_operation_not_allowed_description": "Updating declarative resources is not permitted",
	"error.i18nservice.empty_translations": "Empty translations",
	"error.i18nservice.empty_translations_description": "At least one translation must be provided",
	"error.i18nservice.internal_server_error": "Internal server error",
	"error.i18nservice.internal_server_error_description": "An unexpected error occurred while processing the request",
	"error.i18nservice.invalid_key": "Invalid key format",
	"error.i18nservice.invalid_key_description": "The key can only contain alphanumeric characters, dots, underscores, and hyphens",
	"error.i18nservice.invalid_language": "Invalid language tag format",
	"error.i18nservice.invalid_language_description": "The language tag must follow canonical BCP 47 format (e.g., 'en', 'es', 'fr-CA')",
	"error.i18nservice.invalid_namespace": "Invalid namespace format",
	"error.i18nservice.invalid_namespace_description": "The namespace can only contain alphanumeric characters, underscores, and hyphens",
	"error.i18nservice.invalid_request_description": "The request body is malformed or contains invalid data",
	"error.i18nservice.invalid_request_format": "Invalid request format",
	"error.i18nservice.missing_language": "Missing language code",
	"error.i18nservice.missing_language_description": "Language code is required",
	"error.i18nservice.missing_value": "Missing translation value",
	"error.i18nservice.missing_value_description": "Translation value is required",
	"error.i18nservice.translation_not_found": "Translation not found",
	"error.i18nservice.translation_not_found_description": "The requested translation does not exist for the specified language, namespace, and key",
	"error.internal_server_error": "Internal server error",
	"error.internal_server_error_description": "An unexpected error occurred while processing the request",
}
