// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authnprovidermock

import (
	"github.com/asgardeo/thunder/internal/authnprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthnProviderInterfaceMock creates a new instance of AuthnProviderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthnProviderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthnProviderInterfaceMock {
	mock := &AuthnProviderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthnProviderInterfaceMock is an autogenerated mock type for the AuthnProviderInterface type
type AuthnProviderInterfaceMock struct {
	mock.Mock
}

type AuthnProviderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthnProviderInterfaceMock) EXPECT() *AuthnProviderInterfaceMock_Expecter {
	return &AuthnProviderInterfaceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type AuthnProviderInterfaceMock
func (_mock *AuthnProviderInterfaceMock) Authenticate(identifiers map[string]interface{}, credentials map[string]interface{}, metadata *authnprovider.AuthnMetadata) (*authnprovider.AuthnResult, *authnprovider.AuthnProviderError) {
	ret := _mock.Called(identifiers, credentials, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *authnprovider.AuthnResult
	var r1 *authnprovider.AuthnProviderError
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}, map[string]interface{}, *authnprovider.AuthnMetadata) (*authnprovider.AuthnResult, *authnprovider.AuthnProviderError)); ok {
		return returnFunc(identifiers, credentials, metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}, map[string]interface{}, *authnprovider.AuthnMetadata) *authnprovider.AuthnResult); ok {
		r0 = returnFunc(identifiers, credentials, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authnprovider.AuthnResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]interface{}, map[string]interface{}, *authnprovider.AuthnMetadata) *authnprovider.AuthnProviderError); ok {
		r1 = returnFunc(identifiers, credentials, metadata)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*authnprovider.AuthnProviderError)
		}
	}
	return r0, r1
}

// AuthnProviderInterfaceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type AuthnProviderInterfaceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - identifiers map[string]interface{}
//   - credentials map[string]interface{}
//   - metadata *authnprovider.AuthnMetadata
func (_e *AuthnProviderInterfaceMock_Expecter) Authenticate(identifiers interface{}, credentials interface{}, metadata interface{}) *AuthnProviderInterfaceMock_Authenticate_Call {
	return &AuthnProviderInterfaceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", identifiers, credentials, metadata)}
}

func (_c *AuthnProviderInterfaceMock_Authenticate_Call) Run(run func(identifiers map[string]interface{}, credentials map[string]interface{}, metadata *authnprovider.AuthnMetadata)) *AuthnProviderInterfaceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		var arg2 *authnprovider.AuthnMetadata
		if args[2] != nil {
			arg2 = args[2].(*authnprovider.AuthnMetadata)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthnProviderInterfaceMock_Authenticate_Call) Return(authnResult *authnprovider.AuthnResult, authnProviderError *authnprovider.AuthnProviderError) *AuthnProviderInterfaceMock_Authenticate_Call {
	_c.Call.Return(authnResult, authnProviderError)
	return _c
}

func (_c *AuthnProviderInterfaceMock_Authenticate_Call) RunAndReturn(run func(identifiers map[string]interface{}, credentials map[string]interface{}, metadata *authnprovider.AuthnMetadata) (*authnprovider.AuthnResult, *authnprovider.AuthnProviderError)) *AuthnProviderInterfaceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributes provides a mock function for the type AuthnProviderInterfaceMock
func (_mock *AuthnProviderInterfaceMock) GetAttributes(token string, requestedAttributes []string, metadata *authnprovider.GetAttributesMetadata) (*authnprovider.GetAttributesResult, *authnprovider.AuthnProviderError) {
	ret := _mock.Called(token, requestedAttributes, metadata)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributes")
	}

	var r0 *authnprovider.GetAttributesResult
	var r1 *authnprovider.AuthnProviderError
	if returnFunc, ok := ret.Get(0).(func(string, []string, *authnprovider.GetAttributesMetadata) (*authnprovider.GetAttributesResult, *authnprovider.AuthnProviderError)); ok {
		return returnFunc(token, requestedAttributes, metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string, *authnprovider.GetAttributesMetadata) *authnprovider.GetAttributesResult); ok {
		r0 = returnFunc(token, requestedAttributes, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authnprovider.GetAttributesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string, *authnprovider.GetAttributesMetadata) *authnprovider.AuthnProviderError); ok {
		r1 = returnFunc(token, requestedAttributes, metadata)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*authnprovider.AuthnProviderError)
		}
	}
	return r0, r1
}

// AuthnProviderInterfaceMock_GetAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributes'
type AuthnProviderInterfaceMock_GetAttributes_Call struct {
	*mock.Call
}

// GetAttributes is a helper method to define mock.On call
//   - token string
//   - requestedAttributes []string
//   - metadata *authnprovider.GetAttributesMetadata
func (_e *AuthnProviderInterfaceMock_Expecter) GetAttributes(token interface{}, requestedAttributes interface{}, metadata interface{}) *AuthnProviderInterfaceMock_GetAttributes_Call {
	return &AuthnProviderInterfaceMock_GetAttributes_Call{Call: _e.mock.On("GetAttributes", token, requestedAttributes, metadata)}
}

func (_c *AuthnProviderInterfaceMock_GetAttributes_Call) Run(run func(token string, requestedAttributes []string, metadata *authnprovider.GetAttributesMetadata)) *AuthnProviderInterfaceMock_GetAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 *authnprovider.GetAttributesMetadata
		if args[2] != nil {
			arg2 = args[2].(*authnprovider.GetAttributesMetadata)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthnProviderInterfaceMock_GetAttributes_Call) Return(getAttributesResult *authnprovider.GetAttributesResult, authnProviderError *authnprovider.AuthnProviderError) *AuthnProviderInterfaceMock_GetAttributes_Call {
	_c.Call.Return(getAttributesResult, authnProviderError)
	return _c
}

func (_c *AuthnProviderInterfaceMock_GetAttributes_Call) RunAndReturn(run func(token string, requestedAttributes []string, metadata *authnprovider.GetAttributesMetadata) (*authnprovider.GetAttributesResult, *authnprovider.AuthnProviderError)) *AuthnProviderInterfaceMock_GetAttributes_Call {
	_c.Call.Return(run)
	return _c
}
